import fs from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawn,spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const kujo=process.env.KUJO_BIN||'kujo',root=fs.mkdtempSync(join(tmpdir(),'effect-continuation-'));
const hash=x=>createHash('sha256').update(x).digest('hex');
const env={...process.env,DISPATCH_OFFLINE_FIXTURE:'true',DISPATCH_ALLOW_ANY_OUTPUT_ROOT:'true'};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v));
function run(dir,mode,...args){const p=spawnSync(kujo,['run','tests/effect_continuation_fixture.kujo',dir,mode,...args],{encoding:'utf8',env,timeout:60000,maxBuffer:4*1024*1024});assert.equal(p.status,0,p.stdout+p.stderr);assert.equal(p.stderr,'');return JSON.parse(p.stdout)}
function setup(name,extra={}){const dir=join(root,name);fs.mkdirSync(dir);const now=Math.floor(Date.now()/1000);write(join(dir,'host.json'),{...extra,intents:['A','B','C','D'].map(id=>({operation:'create',target_sha256:hash(dir+'/sink.db'),scope_sha256:hash('scope'),key_sha256:hash(id),request_sha256:hash('request-'+id),precondition_sha256:hash('empty'),valid_from:now-10,valid_until:now+3500}))});assert.equal(run(dir,'init').ok,true);return dir}
const a=setup('valid');assert.equal(run(a,'select').ok,true);assert.equal(run(a,'admit').ok,true);assert.equal(run(a,'count').length,3);assert.equal(run(a,'admit').ok,false);assert.equal(run(a,'select','D').ok,false);assert.equal(run(a,'generic').ok,false);
const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);
const pointer=dir=>read(join(dir,'pointer.json'));const statePath=dir=>join(pointer(dir).run_dir,'state.json');
const state=dir=>JSON.parse(fs.readFileSync(statePath(dir),'utf8').split('\n').slice(1).join('\n'));
function alterState(dir,fn){const s=state(dir);fn(s);fs.writeFileSync(statePath(dir),'DISPATCH_ASSURANCE_STATE_V1BETA1\n'+canonical(s))}
function alter(dir,fn){const c=read(join(dir,'host.json'));fn(c);write(join(dir,'host.json'),c)}
function observation(dir,index,fn){alter(dir,c=>{const set=JSON.parse(c.effect_set.set_raw),old=read(join(dir,'artifacts',set.observations[index].slice(7)+'.json'));fn(old);const raw=canonical(old),digest=hash(raw);fs.writeFileSync(join(dir,'artifacts',digest+'.json'),raw);set.observations[index]='sha256:'+digest;c.effect_set.set_raw=canonical(set)})}
async function killAt(dir,mode){const p=spawn(kujo,['run','tests/effect_continuation_fixture.kujo',dir,mode],{env,stdio:['ignore','pipe','pipe']});let out='',err='';const timeout=setTimeout(()=>p.kill('SIGKILL'),30000);p.stdout.on('data',b=>{out+=b;if(out.includes('CRASH:'+mode))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);const status=await new Promise(r=>p.on('exit',(code,signal)=>r({code,signal})));clearTimeout(timeout);assert.ok(out.includes('CRASH:'+mode),out+err);assert.equal(status.signal,'SIGKILL');assert.equal(err,'')}
let ready=0;
function freshController(dir){return new Promise((resolve,reject)=>{const p=spawn(kujo,['run','tests/effect_continuation_fixture.kujo',dir,'race'],{env,stdio:['ignore','pipe','pipe']});let out='',err='';let announced=false;p.stdout.on('data',b=>{out+=b;if(out.includes('READY')&&!announced){announced=true;ready++;if(ready===2){assert.equal(state(dir).effect_continuation.status,'selected');fs.writeFileSync(join(dir,'race-release'),'go')}}});p.stderr.on('data',b=>err+=b);p.on('exit',code=>{try{assert.equal(code,0,out+err);assert.equal(err,'');resolve(JSON.parse(out.trim().split('\n').at(-1)))}catch(e){reject(e)}})})}
const proofs=['valid-prefix-only-C','repeat-denied','D-denied','parent-replay-denied'];
for(const id of ['A','B','D']){const d=setup('deny-'+id);assert.equal(run(d,'select',id).ok,false);assert.equal(run(d,'count').length,2);proofs.push('cannot-select-'+id)}
const unknown=setup('unknown-prefix');observation(unknown,1,o=>o.state='unknown');assert.equal(run(unknown,'select').ok,false);proofs.push('unknown-prefix-blocks');
const crashA=setup('crash-A');await killAt(crashA,'before_selection');assert.equal(state(crashA).effect_continuation,undefined);assert.equal(fs.existsSync(join(pointer(crashA).run_dir,'effect-attempts')),false);assert.equal(run(crashA,'count').length,2);assert.equal(run(crashA,'select').ok,true);proofs.push('A-no-phantom');
const crashB=setup('crash-B');await killAt(crashB,'after_selection');const surviving=state(crashB).effect_continuation.selection;assert.equal(run(crashB,'count').length,2);assert.equal(run(crashB,'admit').ok,true);assert.deepEqual(state(crashB).effect_continuation.selection,surviving);proofs.push('B-same-attempt');
for(const point of ['after_admission','after_mutation','after_observation']){const d=setup('crash-'+point);assert.equal(run(d,'select').ok,true);const bytes=fs.readFileSync(join(pointer(d).run_dir,'effect-attempts',state(d).effect_continuation.selection.attempt_id+'.json'));await killAt(d,point);assert.equal(run(d,'count').length,point==='after_admission'?2:3);assert.equal(state(d).effect_continuation.status,point==='after_observation'?'observed':'admitted');assert.equal(run(d,'admit').ok,false);const inspected=run(d,'inspect');assert.equal(inspected.ok,true,JSON.stringify(inspected));assert.equal(inspected.current_observation.observed_state,point==='after_admission'?'not_started':'committed');assert.equal(run(d,'admit').ok,false);assert.equal(run(d,'select','D').ok,false);assert.deepEqual(fs.readFileSync(join(pointer(d).run_dir,'effect-attempts',state(d).effect_continuation.selection.attempt_id+'.json')),bytes);assert.equal(run(d,'count').length,point==='after_admission'?2:3);proofs.push(point+'-no-replay')}
const race=setup('race');assert.equal(run(race,'select').ok,true);const raced=await Promise.all([freshController(race),freshController(race)]);assert.equal(raced.filter(x=>x.ok).length,1,JSON.stringify(raced));assert.equal(run(race,'count').length,3);assert.equal(fs.readdirSync(join(pointer(race).run_dir,'effect-attempts')).filter(f=>f.endsWith('.claim')).length,1);assert.deepEqual(run(race,'audit'),run(race,'count'));const events=fs.readFileSync(join(pointer(race).run_dir,'control-events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(events.filter(e=>e.kind==='effect_admitted').length,1);proofs.push('two-fresh-controllers-one-admission');
const hostChanges={registration:c=>c.effect_set.registration.revision='2',plan:c=>c.effect_set.plan.effects[2].effect_id='X',target:c=>c.effect_set.sink_path+='.other',authority:c=>c.descriptor.authority_sha256=hash('other'),config:c=>c.descriptor.verifier_version='2',revocation:c=>c.status='revoked',environment:c=>c.effect_set.environment_valid=false,'environment-ref':c=>c.effect_set.environment_ref='sha256:'+hash('other'),'set':c=>{const set=JSON.parse(c.effect_set.set_raw);set.observations[0]=null;c.effect_set.set_raw=canonical(set)},'preservation':c=>c.effect_set.plan.preserve_until=1};
for(const [name,change] of Object.entries(hostChanges)){const d=setup('stale-'+name);assert.equal(run(d,'select').ok,true);alter(d,change);assert.equal(run(d,'admit').ok,false,name);assert.equal(run(d,'count').length,2);assert.equal(state(d).effect_continuation.status,'selected');proofs.push('stale-'+name)}
for(const name of ['revision','journal','selected-state','attempt','control','preservation','selection-removal']){const d=setup('state-'+name);assert.equal(run(d,'select').ok,true);alterState(d,s=>{if(name==='revision'){s.revision++;s.human_intervention.state_revision++}if(name==='journal')s.control_journal.last_sha256=hash('bad');if(name==='selected-state')s.steps[0].execution_result.effects[2].state='started';if(name==='attempt')s.steps[0].control_attempt=2;if(name==='control')s.current_control_boundary.status='closed';if(name==='preservation')s.current_control_boundary.preservation.retain_until='2000-01-01T00:00:00Z';if(name==='selection-removal'){delete s.effect_continuation;s.required_features=['effect-assurance-negotiation/v1beta1']}});if(name==='selection-removal')assert.equal(run(d,'select').ok,false);else assert.equal(run(d,'admit').ok,false,name);assert.equal(run(d,'count').length,2);proofs.push('state-'+name)}
for(const field of ['status','environment']){const d=setup('final-'+field);assert.equal(run(d,'select').ok,true);assert.equal(run(d,'change-after-admission:'+field).ok,false);assert.equal(run(d,'count').length,2);assert.equal(state(d).effect_continuation.status,'admitted');assert.equal(run(d,'admit').ok,false);proofs.push('final-revalidation-'+field)}
const expired=setup('expired',{evidence_seconds:4});assert.equal(run(expired,'select').ok,true);const original=state(expired).effect_continuation.selection;await new Promise(r=>setTimeout(r,4200));assert.equal(run(expired,'admit').ok,false);assert.equal(run(expired,'count').length,2);assert.deepEqual(state(expired).effect_continuation.selection,original);proofs.push('actual-evidence-expiry');
const delayed=setup('expires-after-admission',{evidence_seconds:5});assert.equal(run(delayed,'select').ok,true);assert.equal(run(delayed,'expire-after-admission').ok,false);assert.equal(run(delayed,'audit').length,2);proofs.push('expiry-after-admission');
for(const dir of [a,crashA,crashB,race])assert.deepEqual(run(dir,'audit'),run(dir,'count'));

// A claim surviving an interrupted admission publication must still be one-use.
const orphan=setup('orphan-claim');assert.equal(run(orphan,'select').ok,true);const ostate=state(orphan);fs.writeFileSync(join(pointer(orphan).run_dir,'effect-attempts',ostate.effect_continuation.selection.attempt_id+'.claim'),'orphan',{flag:'wx'});assert.equal(run(orphan,'admit').ok,false);assert.equal(run(orphan,'audit').length,2);proofs.push('orphan-claim-denies');
const retained=setup('retained-evidence-removed');assert.equal(run(retained,'select').ok,true);const rs=state(retained).effect_continuation.selection;const sidecar=read(join(pointer(retained).run_dir,'effect-artifacts',rs.binding.set_ref.slice(7)+'.json'));fs.unlinkSync(join(pointer(retained).run_dir,'effect-artifacts',sidecar.observations[0].slice(7)+'.json'));assert.equal(run(retained,'admit').ok,false);proofs.push('retained-evidence-required');
env.DISPATCH_STATE_BACKEND='sqlite';const database=setup('sqlite-state');delete env.DISPATCH_STATE_BACKEND;assert.equal(run(database,'select').ok,true);fs.writeFileSync(statePath(database),'{}');assert.equal(run(database,'admit').ok,true);assert.equal(run(database,'admit').ok,false);assert.deepEqual(run(database,'audit'),run(database,'count'));proofs.push('sqlite-authority-over-json-mirror');
// Execute the actual baseline reader: it cannot ignore the new required feature.
const older=join(root,'baseline-reader');fs.mkdirSync(older);const archive=spawnSync('git',['archive','8fbc5fa930ff5d1ffdc833bc07f9766192711b36'],{maxBuffer:64*1024*1024});assert.equal(archive.status,0);const unpack=spawnSync('tar',['-x','-C',older],{input:archive.stdout});assert.equal(unpack.status,0);fs.writeFileSync(join(older,'probe.kujo'),'from src.core.state import load_run_state\nargs := args()\ntry {print(to_json(load_run_state(args[0],args[1])))} except err {print(to_json({"ok":false}))}\n');
for(const dir of [a,database]){const p=spawnSync(kujo,['run','probe.kujo',join(dir,'runs'),pointer(dir).run_id],{cwd:older,env,encoding:'utf8',timeout:60000});assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).ok,false)}proofs.push('actual-baseline-reader-refuses-new-state');
console.log(JSON.stringify({ok:true,root,checks:proofs.length,proofs}));
