import {fs,join,resolve,spawn,assert,kujo,root,env,write,fixture,run,state,setup,program,policy,gop,pop,actor,patch,op,command} from './static_policy_helpers.mjs';
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)};let serial=0;
const node=id=>({...program(id),terminal_contract:'program-attempt/v1alpha1',max_attempts:2,on_unsuccessful:{action:'retry_same_node'}});
const opts=limit=>({graph_policy:policy([],[],limit),graph_accounting:'dispatch.graph-attempt-accounting/v1alpha1'});
async function fresh(d,request={},extra={},marker=null,mode='policy-op',id='graph'){
 const file=join(d,'fresh-'+serial+++'.json');write(file,request);
 return await new Promise((done,reject)=>{const p=spawn(kujo,['run',fixture,d,mode,id,file],{env:{...env,...extra}});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),180000);p.stdout.on('data',b=>{out+=b;if(marker&&out.includes(marker))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);p.on('close',(code,signal)=>{clearTimeout(timer);try{assert.equal(err,'');if(marker){assert.ok(out.includes(marker),out);assert.equal(signal,'SIGKILL');done(null)}else{assert.equal(code,0,out);done(JSON.parse(out))}}catch(e){reject(e)}})})
}
function assess(d,id,action){const r=pop(d,'attempt',id,'assess',{action});assert.equal(r.ok,true,JSON.stringify(r));return {kind:'attempt',id,action,operation:'apply',candidate:r.candidate,actor}}
function repair(d,id='graph'){const p=run(d,'op',id,{operation:'recovery-plan'});assert.equal(p.ok,true,JSON.stringify(p));assert.ok(p.plan.repairs.length);const r=run(d,'op',id,{operation:'recovery-apply',plan:p.plan});assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.continuation,'not_authorized')}
// Install crash timing in an isolated copy before authority digests are anchored.
const original=process.cwd(),controllers=join(root,'controllers'),copy=join(controllers,'dispatch');fs.mkdirSync(copy,{recursive:true});fs.cpSync(resolve('src'),join(copy,'src'),{recursive:true});fs.mkdirSync(join(copy,'tests'));fs.copyFileSync(resolve(fixture),join(copy,fixture));for(const dir of ['schemas','examples'])fs.symlinkSync(resolve(dir),join(copy,dir));for(const name of ['workcell','eval'])fs.symlinkSync(resolve('../'+name),join(controllers,name));
const journal=join(copy,'src/core/control_journal.kujo');let code=fs.readFileSync(journal,'utf8'),point='    append_file(path, line)';assert.ok(code.includes(point));fs.writeFileSync(journal,code.replace(point,'    if env("ATTEMPT_RECORD_CRASH") == kind {print("CRASH:immutable-attempt-record");sleep(30000)}\n'+point));process.chdir(copy);env.KUJO_MODULE_PATH=[copy,resolve(original,'..'),resolve(original,'../workcell'),resolve(original,'../eval')].join(':');
const d=setup('bound-descendant',[node('B'),{...program('D',['B']),accept_terminal:{B:['failed']}}],opts(3));patch(join(d,'B/host.json'),c=>c.require_resource=true);run(d,'drive');await fresh(d,{}, {NODE_TARGET:'D',NODE_CRASH:'before_node_binding'},'CRASH:before_node_binding','drive');assert.equal(pop(d,'attempt','B','assess',{action:'retry'}).ok,false);pass('downstream reservation blocks retry before child binding');const binding=run(d,'op','D',{operation:'inputs-assess'});assert.equal(binding.ok,true,JSON.stringify(binding));assert.equal(run(d,'op','D',{operation:'inputs-bind',binding:binding.binding}).ok,true);assert.equal(state(d).node_dispatches.D,undefined);assert.ok(state(d,'D').node_input_binding);assert.equal((await fresh(d,assess(d,'D','release'))).ok,true);const retry=pop(d,'attempt','B','assess',{action:'retry'});assert.equal(retry.ok,false,JSON.stringify(retry));pass('retry cannot retire a terminal already bound by an undispatched program descendant');process.chdir(original);console.log(JSON.stringify({ok:true,checks:proofs.length,proofs,root}));
