import {fs,join,resolve,spawn,assert,kujo,root,env,write,fixture,run,state,setup,program,policy,gop,pop,actor,patch,op,command} from './static_policy_helpers.mjs';
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)};let serial=0;
const node=id=>({...program(id),terminal_contract:'program-attempt/v1alpha1',max_attempts:2,on_unsuccessful:{action:'retry_same_node'}});
const opts=limit=>({graph_policy:policy([],[],limit),graph_accounting:'dispatch.graph-attempt-accounting/v1alpha1'});
async function fresh(d,request={},extra={},marker=null,mode='policy-op',id='graph'){
 const file=join(d,'fresh-'+serial+++'.json');write(file,request);
 return await new Promise((done,reject)=>{const p=spawn(kujo,['run',fixture,d,mode,id,file],{env:{...env,...extra}});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),180000);p.stdout.on('data',b=>{out+=b;if(marker&&out.includes(marker))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);p.on('close',(code,signal)=>{clearTimeout(timer);try{assert.equal(err,'');if(marker){assert.ok(out.includes(marker),out);assert.equal(signal,'SIGKILL');done(null)}else{assert.equal(code,0,out);done(JSON.parse(out))}}catch(e){reject(e)}})})
}
function assess(d,id,action){const r=pop(d,'attempt',id,'assess',{action});assert.equal(r.ok,true,JSON.stringify(r));return {kind:'attempt',id,action,operation:'apply',candidate:r.candidate,actor}}
function repair(d,id='graph'){const p=run(d,'op',id,{operation:'recovery-plan'});assert.equal(p.ok,true,JSON.stringify(p));assert.ok(p.plan.repairs.length);const r=run(d,'op',id,{operation:'recovery-apply',plan:p.plan});assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.continuation,'not_authorized')}
// Install crash timing in an isolated copy before authority digests are anchored.
const original=process.cwd(),controllers=join(root,'controllers'),copy=join(controllers,'dispatch');fs.mkdirSync(copy,{recursive:true});fs.cpSync(resolve('src'),join(copy,'src'),{recursive:true});fs.mkdirSync(join(copy,'tests'));fs.copyFileSync(resolve(fixture),join(copy,fixture));for(const dir of ['schemas','examples'])fs.symlinkSync(resolve(dir),join(copy,dir));for(const name of ['workcell','eval'])fs.symlinkSync(resolve('../'+name),join(controllers,name));
const journal=join(copy,'src/core/control_journal.kujo');let code=fs.readFileSync(journal,'utf8'),point='    append_file(path, line)';assert.ok(code.includes(point));fs.writeFileSync(journal,code.replace(point,'    if env("ATTEMPT_RECORD_CRASH") == kind {print("CRASH:immutable-attempt-record");sleep(30000)}\n'+point));process.chdir(copy);env.KUJO_MODULE_PATH=[copy,resolve(original,'..'),resolve(original,'../workcell'),resolve(original,'../eval')].join(':');
const r=setup('last-unit',[node('B'),node('C')],opts(1));const candidates=[assess(r,'B','reserve'),assess(r,'C','reserve')];const race=await Promise.all(candidates.map(c=>fresh(r,c)));assert.equal(race.filter(v=>v.ok).length,1,JSON.stringify(race));const winner=race[0].ok?'B':'C';assert.equal(gop(r,'graph-assess').candidate.budget.reserved,1);assert.equal(gop(r,'graph-assess').candidate.budget.available,0);pass('two fresh controllers reserve exactly one last graph unit');
const release=assess(r,winner,'release');const releases=await Promise.all([fresh(r,release),fresh(r,release)]);assert.equal(releases.filter(v=>v.ok).length,1);assert.equal(gop(r,'graph-assess').candidate.budget.available,1);assert.equal(state(r).graph_attempts[winner].length,1);pass('release contention records one release and restores only never-dispatched capacity');
const a=setup('reserve-crash',[node('B')],opts(2));await fresh(a,{}, {NODE_TARGET:'B',NODE_CRASH:'after_attempt_reservation'},'CRASH:after_attempt_reservation','drive');assert.equal(state(a).graph_attempts.B[0].dispatch,null);assert.equal(state(a,'B').node_input_binding,undefined);assert.equal((await fresh(a,assess(a,'B','release'))).ok,true);assert.equal(fs.existsSync(join(a,'B/executions.log')),false);pass('crash A: durable reservation before binding releases without phantom execution');
const bound=setup('bound-undispatched-release',[node('B')],opts(2));await fresh(bound,{}, {NODE_TARGET:'B',NODE_CRASH:'after_node_binding'},'CRASH:after_node_binding','drive');assert.ok(state(bound,'B').node_input_binding);assert.equal(state(bound).graph_attempts.B[0].dispatch,null);assert.equal((await fresh(bound,assess(bound,'B','release'))).ok,true);assert.equal((await fresh(bound,{}, {},null,'start','B')).ok,false);assert.equal(fs.existsSync(join(bound,'B/executions.log')),false);pass('bound but undispatched reservation releases; its surviving input binding grants no admission');
for(const boundary of ['before_child_load','before_node_admission','after_node_admission']){
 const d=setup(boundary,[node('B')],opts(2));await fresh(d,{}, {NODE_TARGET:'B',NODE_CRASH:'after_node_start_requested'},'CRASH:after_node_start_requested','drive');
 if(boundary!=='before_child_load')await fresh(d,{}, {NODE_CRASH:boundary},'CRASH:'+boundary,'start','B');
 assert.equal(gop(d,'graph-assess').candidate.budget.consumed,1);assert.equal(pop(d,'attempt','B','assess',{action:'release'}).ok,false);assert.equal(pop(d,'attempt','B','assess',{action:'retry'}).ok,false);assert.equal((await fresh(d,{}, {},null,'drive')).ok,true);assert.equal(fs.existsSync(join(d,'B/executions.log')),false);assert.equal(state(d).graph_attempts.B.length,1);pass('crash '+boundary+': consumed dispatch is not redelivered, released or retried');
}
const retry=setup('retry-race',[node('B')],opts(2));patch(join(retry,'B/host.json'),c=>c.require_resource=true);run(retry,'drive');run(retry,'drive');const choice=assess(retry,'B','retry');const retries=await Promise.all([fresh(retry,choice),fresh(retry,choice)]);assert.equal(retries.filter(v=>v.ok).length,1,JSON.stringify(retries));assert.equal(state(retry).graph_attempts.B.length,2);assert.equal(state(retry).graph_attempts.B[1].ordinal,2);assert.equal(state(retry,'B-retry').node_execution_admission,undefined);pass('same-node retry and next-attempt creation race publishes one new reserved instance');
const lost=setup('mutation-lost',[node('B')],opts(2));run(lost,'drive');assert.equal(op(lost,'B','refresh',{effect_id:'C'}).ok,true);assert.equal(op(lost,'B','select',{effect_id:'C'}).ok,true);const selected=run(lost,'op','B',{operation:'inspect'});await fresh(lost,{operation:'admit',expected:selected.cursor,attempt_id:selected.lifecycle.active},{NODE_CRASH:'after_mutation'},'CRASH:after_mutation','op','B');assert.equal(Number(command('sqlite3',[join(lost,'B/sink.db'),'SELECT count(*) FROM mutation_audit;'])),1);assert.equal(pop(lost,'attempt','B','assess',{action:'retry'}).ok,false);assert.equal(pop(lost,'attempt','B','assess',{action:'release'}).ok,false);assert.equal(gop(lost,'graph-assess').candidate.budget.consumed,1);assert.equal(op(lost,'B','verify',{attempt_id:selected.lifecycle.active}).ok,true);assert.equal(pop(lost,'attempt','B','assess',{action:'retry'}).ok,false);pass('crash E: real SQLite mutation reply lost; consumed accounting cannot authorize replay');
for(const action of ['reserve','release','retry']){
 const d=setup('orphan-'+action,[node('B')],opts(2));
 if(action==='release'){const q=assess(d,'B','reserve');assert.equal((await fresh(d,q)).ok,true)}
 if(action==='retry'){patch(join(d,'B/host.json'),c=>c.require_resource=true);run(d,'drive');run(d,'drive')}
 const q=assess(d,'B',action),kind={reserve:'graph_attempt_reserved',release:'graph_reservation_released',retry:'graph_attempt_retried'}[action];await fresh(d,q,{ATTEMPT_RECORD_CRASH:kind},'CRASH:immutable-attempt-record');repair(d);const reloaded=state(d);assert.ok(reloaded.graph_attempts.B);assert.equal(reloaded.graph_finalization,undefined);assert.equal(fs.existsSync(join(d,'B-retry/executions.log')),false);assert.equal(gop(d,'graph-assess').ok,true);pass('orphan '+action+': immutable record/index gap repaired by fresh controller without execution');
}
const terminalGap=setup('terminal-accounting-gap',[node('B')],opts(2));patch(join(terminalGap,'B/host.json'),c=>c.require_resource=true);run(terminalGap,'drive');assert.ok(state(terminalGap,'B').node_execution_refusal);await fresh(terminalGap,{}, {ATTEMPT_RECORD_CRASH:'node_terminal_observed'},'CRASH:immutable-attempt-record','drive');assert.equal(state(terminalGap).graph_attempts.B[0].terminal,null);repair(terminalGap);assert.equal(state(terminalGap).graph_attempts.B[0].terminal.terminal.outcome,'failed');assert.ok(state(terminalGap).graph_attempts.B[0].dispatch);assert.equal(state(terminalGap).graph_finalization,undefined);pass('crash F: durable terminal observation repairs stale accounting without refund or graph finalization');
const refusalGap=setup('refusal-record-gap',[node('B')],opts(2));patch(join(refusalGap,'B/host.json'),c=>c.require_resource=true);await fresh(refusalGap,{}, {NODE_TARGET:'B',NODE_CRASH:'after_node_start_requested'},'CRASH:after_node_start_requested','drive');await fresh(refusalGap,{}, {ATTEMPT_RECORD_CRASH:'node_execution_refused'},'CRASH:immutable-attempt-record','start','B');repair(refusalGap,'B');assert.ok(state(refusalGap,'B').node_execution_refusal);assert.equal(state(refusalGap,'B').node_execution_admission,undefined);assert.equal((await fresh(refusalGap,{}, {},null,'start','B')).ok,false);run(refusalGap,'drive');assert.equal(state(refusalGap).graph_attempts.B[0].terminal.terminal.outcome,'failed');pass('orphan child refusal remains sealed through exact retained-host repair');
process.chdir(original);console.log(JSON.stringify({ok:true,checks:proofs.length,proofs,root}));
