import {setup,program,evaluator,human,policy,branch,routed,accepted,run,gop,finishProgram,finishEval,finishHuman,finishGraph,apply,assert,state,root,edge,pop,actor} from './static_policy_helpers.mjs';
const opts=(p)=>({graph_policy:p,graph_accounting:'dispatch.graph-attempt-accounting/v1alpha1'});const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)};
const d=setup('branch-units',[program('A'),routed(evaluator('E','A'),'quality'),program('B',['E'],[edge('A')]),accepted(program('R',['E']),'E',['failed'])],opts(policy([branch('quality','E','evaluation_verdict',{pass:['B'],fail:['R']})],[],2)));
run(d,'drive');finishProgram(d,'A');run(d,'drive');finishEval(d,'E');apply(d,'branch','quality');assert.equal(gop(d,'graph-assess').candidate.budget.consumed,1);run(d,'drive');finishProgram(d,'B');run(d,'drive');finishGraph(d);const outcome=state(d).graph_finalization.candidate;assert.equal(outcome.budget.consumed,2);assert.equal(state(d).graph_attempts.R,undefined);assert.equal(state(d).graph_attempts.E,undefined);assert.equal(outcome.nodes.find(n=>n.node_id==='R').reason,'not_selected');pass('Eval branch activation consumes zero program units; inactive repair node has no attempt');
const group={id:'SG',members:['B'],entry:['A'],policy:'required-success'};
const s=setup('group-units',[program('A'),program('B',['A'],[edge('A')]),{...program('C',['B'],[edge('B')]),after_subgraphs:['SG']},human('H',['C'])],opts(policy([],[group],3)));
run(s,'drive');finishProgram(s,'A');run(s,'drive');finishProgram(s,'B');run(s,'drive');assert.equal(gop(s,'graph-assess').candidate.budget.consumed,2);apply(s,'subgraph','SG');assert.equal(gop(s,'graph-assess').candidate.budget.consumed,2);run(s,'drive');finishProgram(s,'C');run(s,'drive');finishHuman(s,'H');finishGraph(s);assert.equal(state(s).graph_finalization.candidate.budget.consumed,3);assert.equal(state(s).graph_attempts.H,undefined);pass('subgraph receipt adds no execution unit; human decision is separate from three member dispatches');
const optional=setup('optional-reserved',[program('A',[],[],true)],opts(policy([],[],1)));const c=pop(optional,'attempt','A','assess',{action:'reserve'});assert.equal(c.ok,true,JSON.stringify(c));assert.equal(pop(optional,'attempt','A','apply',{action:'reserve',candidate:c.candidate,actor}).ok,true);assert.equal(gop(optional,'graph-assess').candidate.outcome,'blocked');assert.equal(gop(optional,'optional-cancel',{node_id:'A',actor}).ok,false);const release=pop(optional,'attempt','A','assess',{action:'release'});assert.equal(pop(optional,'attempt','A','apply',{action:'release',candidate:release.candidate,actor}).ok,true);assert.equal(gop(optional,'optional-cancel',{node_id:'A',actor}).ok,true);finishGraph(optional);assert.equal(state(optional).graph_finalization.candidate.budget.consumed,0);assert.equal(pop(optional,'attempt','A','assess',{action:'reserve'}).ok,false);pass('held optional reservation prevents graph sealing; release and cancellation remain explicit');
console.log(JSON.stringify({ok:true,checks:proofs.length,proofs,root}));
