import Ajv from '../interop/typescript-participant/node_modules/ajv/dist/2020.js';
import {setup,program,policy,run,pop,actor,assert,state,root,read,write,join,finishProgram,finishGraph,gop,edge,patch,fs} from './static_policy_helpers.mjs';
const accounting='dispatch.graph-attempt-accounting/v1alpha1';
const retry=(id,deps=[],inputs=[])=>({...program(id,deps,inputs),terminal_contract:'program-attempt/v1alpha1',max_attempts:2,on_unsuccessful:{action:'retry_same_node'}});
const options=(limit=8)=>({graph_policy:policy([],[],limit),graph_accounting:accounting});
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)};
function apply(d,id,action){const a=pop(d,'attempt',id,'assess',{action});assert.equal(a.ok,true,JSON.stringify(a));const b=pop(d,'attempt',id,'apply',{action,candidate:a.candidate,actor});assert.equal(b.ok,true,JSON.stringify(b));assert.equal(b.continuation,'not_authorized');return b}
function drive(d){const r=run(d,'drive');assert.equal(r.ok,true,JSON.stringify(r));return r}
function refuse(d,id){patch(join(d,id,'host.json'),c=>c.require_resource=true);drive(d);drive(d);assert.ok(state(d,id).node_execution_refusal);assert.equal(state(d,id).node_execution_admission,undefined)}
const d=setup('safe-chain',[program('A'),retry('B',['A'],[edge('A')]),program('C',['B'],[edge('B')])],options(4));
drive(d);finishProgram(d,'A');patch(join(d,'B/host.json'),c=>c.require_resource=true);drive(d);drive(d);
assert.equal(gop(d,'graph-assess').candidate.outcome,'blocked');const first=state(d,'B').node_input_binding;const receipt=state(d,'B').node_execution_refusal;
patch(join(d,'B-retry/host.json'),c=>c.require_resource=true);fs.writeFileSync(join(d,'B-retry/required-resource'),'available');
apply(d,'B','retry');assert.equal(fs.existsSync(join(d,'B-retry/executions.log')),false);drive(d);
const second=state(d,'B-retry').node_input_binding;assert.notEqual(first.consumer.run_id,second.consumer.run_id);assert.deepEqual(first.inputs,second.inputs);assert.deepEqual(first.predecessors,second.predecessors);assert.deepEqual(first.policy,second.policy);assert.equal(second.attempt.ordinal,2);assert.ok(second.attempt.previous_terminal_ref);
finishProgram(d,'B-retry');drive(d);const validate=new Ajv().compile(read('schemas/node-input-binding-v1alpha4.schema.json'));assert.equal(validate(state(d,'C').node_input_binding),true,JSON.stringify(validate.errors));finishProgram(d,'C');drive(d);const assessed=gop(d,'graph-assess');assert.equal(assessed.ok,true,JSON.stringify(assessed));assert.equal(assessed.candidate.budget.consumed,4);assert.equal(assessed.candidate.budget.available,0);assert.ok(assessed.candidate.accounting_ref);finishGraph(d);
assert.deepEqual(state(d,'B').node_execution_refusal,receipt);assert.equal(fs.existsSync(join(d,'B/executions.log')),false);assert.equal(state(d).graph_attempts.B.length,2);assert.equal(state(d).graph_attempts.B[0].terminal.terminal.outcome,'failed');assert.equal(state(d).graph_attempts.B[1].terminal.terminal.outcome,'completed');pass('A to safely refused B1 to independent B2 to C; exact inputs, lineage and exhausted graph finalize');
const exhausted=setup('node-ceiling',[retry('B')],options());refuse(exhausted,'B');apply(exhausted,'B','retry');refuse(exhausted,'B-retry');assert.equal(pop(exhausted,'attempt','B','assess',{action:'retry'}).ok,false);assert.equal(gop(exhausted,'graph-assess').candidate.outcome,'failed');finishGraph(exhausted);assert.equal(state(exhausted).graph_finalization.candidate.budget.consumed,2);pass('two refused attempts exhaust node ceiling; no third attempt and original failures retained');
const budget=setup('graph-ceiling',[retry('B')],options(1));refuse(budget,'B');assert.equal(pop(budget,'attempt','B','assess',{action:'retry'}).ok,false);const blocked=gop(budget,'graph-assess');assert.equal(blocked.candidate.outcome,'blocked');assert.equal(blocked.candidate.budget.consumed,1);assert.equal(blocked.candidate.budget.available,0);pass('graph budget exhaustion blocks retry without refund or fabricated terminal failure');
const revoked=setup('revoked-operator',[retry('B')],options());const candidate=pop(revoked,'attempt','B','assess',{action:'reserve'});patch(join(revoked,'host.json'),c=>c.operator_enabled=false);assert.equal(pop(revoked,'attempt','B','apply',{action:'reserve',candidate:candidate.candidate,actor}).ok,false);assert.equal(state(revoked).graph_attempts,undefined);pass('operator revocation denies reservation without consuming capacity');
const unavailable=setup('missing-retry-artifact',[program('A'),retry('B',['A'],[edge('A')])],options());drive(unavailable);finishProgram(unavailable,'A');patch(join(unavailable,'B/host.json'),c=>c.require_resource=true);drive(unavailable);drive(unavailable);fs.appendFileSync(join(unavailable,'A/output.json'),'changed');assert.equal(pop(unavailable,'attempt','B','assess',{action:'retry'}).ok,false);assert.equal(state(unavailable).graph_attempts.B.length,1);pass('changed producer bytes cannot become a newer retry input');
console.log(JSON.stringify({ok:true,root,checks:proofs.length,proofs}));
