import {fs,join,assert,setup,program,evaluator,human,edge,run,state,read,write,patch,gop,actor,finishProgram,finishEval,finishHuman,finishGraph,humanDecision,decision,complete,finalize} from './heterogeneous_helpers.mjs';
let checks=0;const pass=n=>{checks++;console.log('PASS '+n)};
for(const [action,outcome,nodeOutcome] of [['abort','failed','rejected'],['cancel','cancelled','cancelled']]){
 const d=setup('human-'+action,[human('H',[])]);run(d,'drive');assert.equal(finishHuman(d,'H',action).outcome,nodeOutcome);assert.equal(finishGraph(d).outcome,outcome);assert.equal(state(d).node_completions.H.terminal.outcome,nodeOutcome);pass('human '+action+' retains decision semantics under graph policy');
}
const optional=setup('optional-eval-failure',[program('A'),{...evaluator('E','A'),optional:true},human('H',['A'])]);run(optional,'drive');finishProgram(optional,'A');run(optional,'drive');patch(join(optional,'E','host.json'),v=>v.expected_value=99);assert.equal(finishEval(optional,'E').outcome,'failed');finishHuman(optional,'H');assert.equal(finishGraph(optional).outcome,'completed');assert.equal(state(optional).node_completions.E.terminal.outcome,'failed');pass('optional Eval failure stays failed but does not fail required-success graph');
const policy={policy_id:'review-evaluation',policy_version:'1',policies:[{when:{verdict:'fail'},decide:{disposition:'require_intervention',allowed_actions:['abort'],reason:'Explicit review policy'}}]};
const review=setup('evaluation-review',[program('A'),evaluator('E','A')],{control:policy});run(review,'drive');finishProgram(review,'A');run(review,'drive');patch(join(review,'E','host.json'),v=>v.expected_value=99);run(review,'evaluate','E');assert.equal(gop(review,'node-assess',{node_id:'E'}).ok,false);assert.equal(gop(review,'graph-assess').candidate.outcome,'blocked');assert.equal(state(review).node_completions.E,undefined);pass('Eval fail mapped to review remains blocked, not automatically terminal failure');
const producer=setup('program-failure',[program('A'),program('B',['A'],[edge('A')])]);patch(join(producer,'A','host.json'),v=>v.fail_execution=true);assert.equal(run(producer,'drive').ok,false);assert.equal(gop(producer,'graph-assess').candidate.outcome,'blocked');assert.equal(fs.existsSync(join(producer,'B','executions.log')),false);pass('unfinalized execution failure cannot become success or admit dependent');
const consumer=setup('consumer-failure',[program('A'),program('B',['A'],[edge('A')])]);run(consumer,'drive');finishProgram(consumer,'A');const original=JSON.stringify(state(consumer,'A').parent_finalization);patch(join(consumer,'B','host.json'),v=>v.fail_execution=true);assert.equal(run(consumer,'drive').ok,false);assert.equal(gop(consumer,'graph-assess').candidate.outcome,'blocked');assert.equal(JSON.stringify(state(consumer,'A').parent_finalization),original);pass('consumer uncertainty leaves successful producer history unchanged');
const scope=setup('optional-scheduling',[program('A'),program('O',['A'],[edge('A')],true),program('B',['O'],[edge('A')])]);assert.equal(gop(scope,'optional-cancel',{node_id:'A',actor}).ok,false);assert.equal(gop(scope,'optional-cancel',{node_id:'O',actor}).ok,true);run(scope,'drive');finishProgram(scope,'A');run(scope,'drive');assert.equal(gop(scope,'graph-assess').candidate.outcome,'blocked');assert.equal(fs.existsSync(join(scope,'B','executions.log')),false);pass('optional cancellation cannot satisfy a success scheduling dependency');
console.log(JSON.stringify({ok:true,checks}));
