import {fs,join,resolve,spawn,assert,kujo,root,env,read,write,fixture,run,state,setup,program,evaluator,human,edge,gop,actor,finishProgram,finishHuman,humanDecision,finishGraph} from './heterogeneous_helpers.mjs';
const proofs=[];const pass=name=>{proofs.push(name);console.log('PASS '+name)};let serial=0;
function request(d,value){const p=join(d,'fresh-request-'+serial+++'.json');write(p,value);return p}
async function child(d,req,extra={},marker=null,mode='graph-op'){const path=request(d,req);return await new Promise((done,reject)=>{const p=spawn(kujo,['run',fixture,d,mode,'graph',path],{env:{...env,...extra}});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),180000);p.stdout.on('data',b=>{out+=b;if(marker&&out.includes(marker))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);p.on('close',(code,signal)=>{clearTimeout(timer);try{assert.equal(err,'');if(marker){assert.ok(out.includes(marker),out);assert.equal(signal,'SIGKILL');done(null)}else{assert.equal(code,0,out);done(JSON.parse(out))}}catch(e){reject(e)}})})}
function repair(d){const p=run(d,'op','graph',{operation:'recovery-plan'});assert.equal(p.ok,true,JSON.stringify(p));assert.ok(p.plan.repairs.length,JSON.stringify(p));const a=run(d,'op','graph',{operation:'recovery-apply',plan:p.plan});assert.equal(a.ok,true,JSON.stringify(a));assert.equal(a.continuation,'not_authorized');return a}
// A private pinned source copy stops between actual immutable publication and index append.
const original=process.cwd(),controllers=join(root,'controllers'),copy=join(controllers,'dispatch');fs.mkdirSync(copy,{recursive:true});fs.cpSync(resolve('src'),join(copy,'src'),{recursive:true});fs.mkdirSync(join(copy,'tests'));fs.copyFileSync(resolve(fixture),join(copy,fixture));for(const dir of ['schemas','examples'])fs.symlinkSync(resolve(dir),join(copy,dir));for(const name of ['workcell','eval'])fs.symlinkSync(resolve('../'+name),join(controllers,name));
const journal=join(copy,'src/core/control_journal.kujo');let code=fs.readFileSync(journal,'utf8');const point='    append_file(path, line)';assert.ok(code.includes(point));code=code.replace(point,'    if env("GRAPH_RECORD_CRASH") == kind {print("CRASH:immutable-graph-record");sleep(30000)}\n'+point);fs.writeFileSync(journal,code);process.chdir(copy);env.KUJO_MODULE_PATH=[copy,resolve(original,'..'),resolve(original,'../workcell'),resolve(original,'../eval')].join(':');
const d=setup('heterogeneous-recovery',[program('A'),evaluator('E','A'),human('H',['A'],[edge('A')])]);run(d,'drive');finishProgram(d,'A');run(d,'drive');run(d,'evaluate','E');const ea=gop(d,'node-assess',{node_id:'E'});assert.equal(ea.ok,true,JSON.stringify(ea));
await child(d,{operation:'node-finalize',node_id:'E',candidate:ea.candidate},{NODE_CRASH:'after_terminal'},'CRASH:after_terminal');assert.equal(state(d).node_completions.E.terminal.outcome,'completed');assert.equal(gop(d,'graph-assess').candidate.outcome,'blocked');pass('Eval terminal reply loss survives a fresh controller without a fake execution');
const decision=humanDecision(d,'H'),ha=gop(d,'node-assess',{node_id:'H',decision});assert.equal(ha.ok,true,JSON.stringify(ha));await child(d,{operation:'node-finalize',node_id:'H',decision,candidate:ha.candidate},{GRAPH_RECORD_CRASH:'node_terminal_observed'},'CRASH:immutable-graph-record');assert.equal(state(d).node_completions.H,undefined);repair(d);assert.equal(state(d).node_completions.H.terminal.outcome,'completed');assert.equal(state(d).graph_finalization,undefined);assert.equal(state(d).status,'paused');pass('actual human terminal orphan repairs exact decision but not graph completion');
const p=run(d,'op','graph',{operation:'recovery-plan'});assert.equal(p.ok,true,JSON.stringify(p));assert.equal(p.plan.repairs.length,0);assert.equal(state(d).graph_finalization,undefined);const candidates=await Promise.all([child(d,{operation:'graph-assess'}),child(d,{operation:'graph-assess'})]);assert.ok(candidates.every(x=>x.ok&&x.candidate.outcome==='completed'));assert.deepEqual(candidates[0].candidate,candidates[1].candidate);pass('all durable terminal facts and recovery still require separate graph decision');
const results=await Promise.all(candidates.map(x=>child(d,{operation:'graph-finalize',candidate:x.candidate,actor})));assert.equal(results.filter(x=>x.ok).length,1,JSON.stringify(results));const events=fs.readFileSync(join(state(d).run_dir,'control-events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(events.filter(x=>x.kind==='graph_finalized').length,1);assert.equal(gop(d,'graph-assess').status,'already_finalized');pass('two fresh finalizers: one exact durable graph terminal transition');
for(const point of ['before_terminal','after_terminal','immutable']){
 const x=setup('graph-crash-'+point,[human('H',[])]);run(x,'drive');finishHuman(x,'H');const a=gop(x,'graph-assess');assert.equal(a.candidate.outcome,'completed');
 const extra=point==='immutable'?{GRAPH_RECORD_CRASH:'graph_finalized'}:{NODE_CRASH:point};await child(x,{operation:'graph-finalize',candidate:a.candidate,actor},extra,point==='immutable'?'CRASH:immutable-graph-record':'CRASH:'+point);
 if(point==='before_terminal'){assert.equal(state(x).graph_finalization,undefined);assert.equal(gop(x,'graph-assess').candidate.outcome,'completed');finishGraph(x)}
 if(point==='immutable'){assert.equal(state(x).graph_finalization,undefined);repair(x)}
 assert.equal(gop(x,'graph-assess').status,'already_finalized');assert.equal(state(x).status,'completed');assert.equal(gop(x,'graph-finalize',{candidate:a.candidate,actor}).ok,false);pass('graph crash '+point+' preserves exact terminal boundary');
}
const pending=setup('optional-dispatch-race',[human('H',[]),program('O',['H'],[],true)]);run(pending,'drive');finishHuman(pending,'H');
await child(pending,{}, {NODE_TARGET:'O',NODE_CRASH:'after_node_start_requested'},'CRASH:after_node_start_requested','drive');assert.equal(state(pending,'O').node_execution_admission,undefined);assert.ok(state(pending).node_dispatches.O);assert.equal(gop(pending,'graph-assess').candidate.outcome,'blocked');assert.equal(gop(pending,'optional-cancel',{node_id:'O',actor}).ok,false);pass('optional outstanding dispatch blocks graph finalization before child admission');
process.chdir(original);console.log(JSON.stringify({ok:true,checks:proofs.length,scenarios:proofs,root}));
