import {fs,join,resolve,spawnSync,spawn,assert,kujo,root,env,hash,read,write,command,fixture,run,state,setup,op,complete,decision,finalize,edge} from './node_composition_helpers.mjs';
const checks=[];
function check(name,fn){fn();checks.push(name);console.error('PASS '+name)}
function host(d,id,patch){const p=join(d,id,'host.json');write(p,{...read(p),...patch})}
function denied(value){assert.equal(value.ok,false,JSON.stringify(value))}
const two=[{id:'A',depends_on:[],inputs:[]},{id:'B',depends_on:['A'],inputs:[edge('A')]}];
const d=setup('two',two);
console.error('ROOT '+d);
check('producer output exists without finalization: consumer blocked',()=>{assert.equal(run(d,'drive').paused,true);assert.ok(fs.existsSync(join(d,'A/output.json')));denied(run(d,'op','B',{operation:'inputs-assess'}));assert.equal(fs.existsSync(join(d,'B/executions.log')),false)});
check('unresolved producer effect prevents finalization',()=>{denied(run(d,'op','A',{operation:'parent-inspect',decision:decision(d,'A')}));});
complete(d,'A');
check('output missing prevents producer finalization',()=>{const p=join(d,'A/output.json');fs.renameSync(p,p+'.saved');denied(run(d,'op','A',{operation:'parent-inspect',decision:decision(d,'A')}));fs.renameSync(p+'.saved',p)});
check('evaluation failure and operator revocation block terminal authority',()=>{const p=join(d,'A/host.json'),original=fs.readFileSync(p);const config=read(p),evaluation=JSON.parse(config.evaluation_raw);evaluation.verdict='fail';config.evaluation_raw=JSON.stringify(evaluation);write(p,config);assert.equal(run(d,'op','A',{operation:'parent-inspect',decision:decision(d,'A')}).candidate.outcome,'failed');denied(run(d,'op','B',{operation:'inputs-assess'}));fs.writeFileSync(p,original);host(d,'A',{operator_enabled:false});denied(run(d,'op','A',{operation:'parent-inspect',decision:decision(d,'A')}));fs.writeFileSync(p,original)});
check('effect completion and passing Eval still do not finalize producer',()=>{denied(run(d,'op','B',{operation:'inputs-assess'}));assert.equal(fs.existsSync(join(d,'B/executions.log')),false)});
finalize(d,'A');
const producerTerminal=JSON.stringify(state(d,'A').parent_finalization);
const candidate=run(d,'op','B',{operation:'inputs-assess'});assert.equal(candidate.ok,true,JSON.stringify(candidate));
check('exact source name type digest revision and producer binding',()=>{for(const [field,value] of [['producer_node','wrong'],['output_name','wrong'],['type_id','wrong'],['content_ref','sha256:'+'0'.repeat(64)],['finalized_revision',0],['producer_subject',{run_id:'wrong',step_id:'action',attempt_id:'1'}]]){const binding=structuredClone(candidate.binding);binding.inputs[0][field]=value;denied(run(d,'op','B',{operation:'inputs-bind',binding}));}assert.equal(state(d,'B').node_input_binding,undefined)});
assert.equal(run(d,'op','B',{operation:'inputs-bind',binding:candidate.binding}).ok,true);
check('binding survives fresh load; artifact mutation and absence deny execution',()=>{assert.deepEqual(state(d,'B').node_input_binding,candidate.binding);const p=join(d,'A/output.json'),bytes=fs.readFileSync(p);fs.writeFileSync(p,'{}');denied(run(d,'drive'));assert.equal(fs.existsSync(join(d,'B/executions.log')),false);fs.unlinkSync(p);denied(run(d,'drive'));fs.writeFileSync(p,bytes);assert.equal(state(d,'B').node_execution_admission,undefined)});
check('stale installed authority denies consumer',()=>{host(d,'B',{status:'revoked'});denied(run(d,'drive'));assert.equal(fs.existsSync(join(d,'B/executions.log')),false);host(d,'B',{status:'active'})});
check('consumer executes independently with pinned provenance',()=>{assert.equal(run(d,'drive').paused,true);assert.equal(read(join(d,'B/output.json')).value,2);assert.deepEqual(read(join(d,'B/output.json')).sources,[candidate.binding.inputs[0].content_ref]);assert.notEqual(state(d,'A').run_id,state(d,'B').run_id);assert.notEqual(read(join(d,'A/host.json')).workspace.workspace_path,read(join(d,'B/host.json')).workspace.workspace_path);assert.ok(state(d,'B').node_execution_admission);assert.equal(state(d,'B').parent_finalization,undefined);assert.equal(state(d).status,'paused');assert.equal(JSON.stringify(state(d,'A').parent_finalization),producerTerminal)});
complete(d,'B');finalize(d,'B');
check('all required independently finalized nodes complete existing DAG',()=>{assert.equal(run(d,'drive').ok,true);assert.equal(state(d).status,'completed');assert.equal(Object.keys(state(d).node_completions).length,2);assert.equal(fs.readFileSync(join(d,'B/executions.log'),'utf8'),'executed\n');assert.deepEqual(state(d,'B').node_input_binding,candidate.binding)});
check('historical consumer provenance cannot become a later producer version',()=>{const p=join(d,'A/output.json'),bytes=fs.readFileSync(p),later={...JSON.parse(bytes),value:99};fs.writeFileSync(p,JSON.stringify(later));const binding=state(d,'B').node_input_binding;assert.deepEqual(binding,candidate.binding);const retained=join(state(d,'B').run_dir,'node-input',binding.inputs[0].content_ref.slice(7)+'.raw');assert.equal(hash(fs.readFileSync(retained)),binding.inputs[0].content_ref.slice(7));assert.equal(read(retained).value,1);denied(run(d,'start','A'));fs.writeFileSync(p,bytes)});
const fan=setup('fanout',[two[0],{id:'C',depends_on:['A'],inputs:[]},two[1]]);
check('completion-only edge does not transfer an artifact',()=>{run(fan,'drive');complete(fan,'A');finalize(fan,'A');run(fan,'drive');assert.equal(read(join(fan,'C/output.json')).value,1);assert.deepEqual(state(fan,'C').node_input_binding.inputs,[]);assert.equal(state(fan,'C').node_input_binding.predecessors.length,1);complete(fan,'C');finalize(fan,'C');run(fan,'drive');assert.equal(read(join(fan,'B/output.json')).value,2);complete(fan,'B');finalize(fan,'B');run(fan,'drive');assert.equal(state(fan).status,'completed')});
const joinGraph=setup('join',[two[0],{id:'B',depends_on:[],inputs:[]},{id:'C',depends_on:['A','B'],inputs:[edge('A','left'),edge('B','right')]}]);
check('bounded join requires both independently finalized producers',()=>{run(joinGraph,'drive');complete(joinGraph,'A');finalize(joinGraph,'A');denied(run(joinGraph,'op','C',{operation:'inputs-assess'}));run(joinGraph,'drive');complete(joinGraph,'B');finalize(joinGraph,'B');run(joinGraph,'drive');assert.equal(read(join(joinGraph,'C/output.json')).value,3);assert.equal(state(joinGraph,'C').node_input_binding.inputs.length,2);complete(joinGraph,'C');finalize(joinGraph,'C');run(joinGraph,'drive');assert.equal(state(joinGraph).status,'completed')});
const fail=setup('consumer-failure',two);run(fail,'drive');complete(fail,'A');finalize(fail,'A');const before=JSON.stringify(state(fail,'A').parent_finalization);host(fail,'B',{fail_execution:true});
check('consumer failure cannot rewrite finalized producer',()=>{denied(run(fail,'drive'));assert.equal(state(fail,'B').status,'failed');assert.equal(JSON.stringify(state(fail,'A').parent_finalization),before);assert.notEqual(state(fail).status,'completed');denied(run(fail,'start','B'));assert.equal(fs.readFileSync(join(fail,'B/executions.log'),'utf8'),'executed\n')});
const failA=setup('producer-failure',two);host(failA,'A',{fail_execution:true});
check('producer execution failure blocks dependent',()=>{denied(run(failA,'drive'));denied(run(failA,'op','B',{operation:'inputs-assess'}));assert.equal(fs.existsSync(join(failA,'B/executions.log')),false)});
async function crash(d,mode,id,point,target=id){return await new Promise((resolve,reject)=>{const child=spawn(kujo,['run',fixture,d,mode,id],{env:{...env,NODE_CRASH:point,NODE_TARGET:target}});let out='',err='';const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('crash marker timeout '+out+err))},60000);child.stdout.on('data',b=>{out+=b;if(out.includes('CRASH:'+point))child.kill('SIGKILL')});child.stderr.on('data',b=>err+=b);child.on('close',()=>{clearTimeout(timer);try{assert.ok(out.includes('CRASH:'+point),out+err);resolve()}catch(e){reject(e)}})})}
for(const point of ['before_node_binding','after_node_binding','after_node_start_requested']){const c=setup(point,two);run(c,'drive');complete(c,'A');finalize(c,'A');await crash(c,'drive','graph',point,'B');assert.equal(fs.existsSync(join(c,'B/executions.log')),false);if(point==='before_node_binding')assert.equal(state(c,'B').node_input_binding,undefined);else assert.ok(state(c,'B').node_input_binding);assert.equal(run(c,'drive').paused,true);assert.equal(fs.readFileSync(join(c,'B/executions.log'),'utf8'),'executed\n');checks.push('fresh controller '+point);console.error('PASS '+checks.at(-1))}
const consumed=setup('consumed-before-execution',two);run(consumed,'drive');complete(consumed,'A');finalize(consumed,'A');await crash(consumed,'drive','graph','after_node_start_requested','B');await crash(consumed,'start','B','after_node_admission');
check('consumed initial admission survives crash without fabricating execution',()=>{assert.ok(state(consumed,'B').node_execution_admission);assert.equal(fs.existsSync(join(consumed,'B/executions.log')),false);assert.equal(run(consumed,'drive').paused,true);denied(run(consumed,'start','B'));assert.equal(fs.existsSync(join(consumed,'B/executions.log')),false);assert.notEqual(state(consumed).status,'completed')});
console.log(JSON.stringify({ok:true,root,checks:checks.length,scenarios:checks}));
