import {fs,join,resolve,spawn,assert,kujo,root,env,hash,read,write,command,fixture,run,state,setup,op,complete,decision,finalize,edge} from './node_composition_helpers.mjs';
const proofs=[];
const two=[{id:'A',depends_on:[],inputs:[]},{id:'B',depends_on:['A'],inputs:[edge('A')]}];
const denied=x=>assert.equal(x.ok,false,JSON.stringify(x));
const path=(d,id)=>join(read(join(d,id==='graph'?'':id,'pointer.json')).run_dir,'state.json');
const record=(name)=>{proofs.push(name);console.error('PASS '+name)};
const prepare=name=>{const d=setup(name,two);assert.equal(run(d,'drive').paused,true);complete(d,'A');finalize(d,'A');return d};
async function child(args,extra={},marker=null){return await new Promise((resolve,reject)=>{const p=spawn(kujo,args,{env:{...env,...extra}});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),180000);p.stdout.on('data',b=>{out+=b;if(marker&&out.includes(marker))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);p.on('close',(code,signal)=>{clearTimeout(timer);try{assert.equal(err,'');if(marker){assert.ok(out.includes(marker),out);assert.equal(signal,'SIGKILL');resolve(null)}else{assert.equal(code,0,out);resolve(JSON.parse(out))}}catch(e){reject(e)}})})}
function repair(d,id){const planned=run(d,'op',id,{operation:'recovery-plan'});assert.equal(planned.ok,true,JSON.stringify(planned));assert.ok(planned.plan.repairs.length,JSON.stringify(planned));const applied=run(d,'op',id,{operation:'recovery-apply',plan:planned.plan});assert.equal(applied.ok,true,JSON.stringify(applied));assert.equal(applied.continuation,'not_authorized');return planned}
let serial=0;
const raced=prepare('fresh-controller-race');
const eligibility=await Promise.all([child(['run',fixture,raced,'op','B',request(raced,{operation:'inputs-assess'})]),child(['run',fixture,raced,'op','B',request(raced,{operation:'inputs-assess'})])]);assert.ok(eligibility.every(x=>x.ok));assert.deepEqual(eligibility[0].binding,eligibility[1].binding);
const results=await Promise.all([child(['run',fixture,raced,'drive','graph']),child(['run',fixture,raced,'drive','graph'])]);assert.ok(results.some(x=>x.ok));assert.equal(fs.readFileSync(join(raced,'B/executions.log'),'utf8'),'executed\n');const b=state(raced,'B');assert.ok(b.node_execution_admission);const admissions=fs.readFileSync(join(b.run_dir,'control-events.jsonl'),'utf8').trim().split('\n').map(JSON.parse).filter(x=>x.kind==='node_execution_admitted');assert.equal(admissions.length,1);assert.ok(results.every(x=>x.ok?x.reason==='node_requires_independent_finalization':x.error?.code==='run_lock_timeout'));console.error(JSON.stringify({contention:results.map(x=>({ok:x.ok,reason:x.reason||x.error?.code})),admissions:admissions.length}));assert.equal(fs.readdirSync(join(b.run_dir,'node-input')).filter(x=>x.endsWith('.claim')).length,1);denied(run(raced,'start','B'));record('two fresh graph controllers: one consumer admission and action');
function request(d,value){const p=join(d,'recovery-request-'+(serial++)+'.json');write(p,value);return p}
// The observation is durable but the consumer still has no terminal authority.
assert.equal(op(raced,'B','refresh',{effect_id:'C'}).ok,true);assert.equal(op(raced,'B','select',{effect_id:'C'}).ok,true);const selected=run(raced,'op','B',{operation:'inspect'}),snapshot=fs.readFileSync(path(raced,'B'));
await child(['run',fixture,raced,'op','B',request(raced,{operation:'admit',expected:selected.cursor,attempt_id:selected.lifecycle.active})],{NODE_CRASH:'after_observation'},'CRASH:after_observation');
assert.equal(state(raced,'B').parent_finalization,undefined);fs.writeFileSync(path(raced,'B'),snapshot);repair(raced,'B');const reloaded=run(raced,'op','B',{operation:'inspect'});assert.equal(reloaded.ok,true,JSON.stringify(reloaded));assert.equal(reloaded.lifecycle.attempts[selected.lifecycle.active].consumed,true);denied(op(raced,'B','admit',{attempt_id:selected.lifecycle.active}));assert.equal(run(raced,'drive').paused,true);assert.equal(state(raced,'B').parent_finalization,undefined);assert.equal(op(raced,'B','refresh',{effect_id:'C'}).ok,true);finalize(raced,'B');assert.equal(run(raced,'drive').ok,true);record('real observation crash: repair retains consumption and requires separate finalization');
// A retained content orphan cannot create an input binding or terminal decision.
const orphan=setup('unreferenced-content',[two[0]]),a=state(orphan,'A');fs.mkdirSync(join(a.run_dir,'node-input'));const raw='{"unreferenced":true}';fs.writeFileSync(join(a.run_dir,'node-input',hash(raw)+'.raw'),raw);const assessed=run(orphan,'op','A',{operation:'recovery-plan'});assert.equal(assessed.ok,true,JSON.stringify(assessed));assert.equal(assessed.plan.repairs.length,0);assert.equal(state(orphan,'A').node_input_binding,undefined);record('raw output orphan cannot synthesize a binding');
// Kill the real immutable-record write in a disposable pinned controller copy.
// Production contains no environment-controlled journal corruption hook.
const original=process.cwd(),controllers=join(root,'controllers'),copy=join(controllers,'dispatch');fs.mkdirSync(copy,{recursive:true});fs.cpSync(resolve('src'),join(copy,'src'),{recursive:true});fs.mkdirSync(join(copy,'tests'));for(const file of [fixture,'tests/resource_eval_worker.kujo'])fs.copyFileSync(resolve(file),join(copy,file));for(const dir of ['schemas','examples'])fs.symlinkSync(resolve(dir),join(copy,dir));for(const name of ['workcell','eval'])fs.symlinkSync(resolve('../'+name),join(controllers,name));
const journal=join(copy,'src/core/control_journal.kujo'),point='    append_file(path, line)';let source=fs.readFileSync(journal,'utf8');assert.ok(source.includes(point));source=source.replace(point,'    if env("NODE_RECORD_CRASH") == kind {print("CRASH:immutable-node-record");sleep(30000)}\n'+point);fs.writeFileSync(journal,source);process.chdir(copy);env.KUJO_MODULE_PATH=[copy,resolve(original,'..'),resolve(original,'../workcell'),resolve(original,'../eval')].join(':');
for(const kind of ['node_inputs_bound','node_terminal_observed']){
 const d=prepare('immutable-'+kind);let args;
 if(kind==='node_inputs_bound'){const input=run(d,'op','B',{operation:'inputs-assess'});assert.equal(input.ok,true);args=['run',fixture,d,'op','B',request(d,{operation:'inputs-bind',binding:input.binding})]}
 else args=['run',fixture,d,'drive','graph'];
 await child(args,{NODE_RECORD_CRASH:kind},'CRASH:immutable-node-record');const target=kind==='node_inputs_bound'?'B':'graph';repair(d,target);assert.equal(fs.existsSync(join(d,'B/executions.log')),false);if(target==='B')assert.ok(state(d,'B').node_input_binding);else assert.ok(state(d).node_completions.A);assert.equal(run(d,'drive').paused,true);assert.equal(fs.readFileSync(join(d,'B/executions.log'),'utf8'),'executed\n');record('real immutable orphan '+kind+' reconciled without implicit execution');
}
process.chdir(original);
console.log(JSON.stringify({ok:true,root,checks:proofs.length,scenarios:proofs}));
