import fs from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const kujo=process.env.KUJO_BIN||'kujo',root=fs.mkdtempSync(join(tmpdir(),'parent-finalization-'));
const hash=x=>createHash('sha256').update(x).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v));
const env={...process.env,KUJO_MODULE_PATH:[resolve('..'),resolve('.'),resolve('../workcell'),resolve('../eval')].join(':'),DISPATCH_OFFLINE_FIXTURE:'true',DISPATCH_ALLOW_ANY_OUTPUT_ROOT:'true'};
function command(program,args,input){const p=spawnSync(program,args,{encoding:'utf8',input,timeout:120000,env,maxBuffer:8*1024*1024});assert.equal(p.status,0,p.stdout+p.stderr);assert.equal(p.stderr,'');return p.stdout.trim()}
let serial=0;const requestFile=(d,r)=>{const p=join(d,'request-'+serial+++'.json');write(p,r);return p};
const fixture='tests/parent_finalization_fixture.kujo';
function run(d,r,mode='operate'){return JSON.parse(command(kujo,['run',fixture,d,mode,requestFile(d,r)]))}
const inspect=d=>run(d,{operation:'inspect'});
function op(d,operation,fields={}){const before=inspect(d);assert.equal(before.ok,true,JSON.stringify(before));return run(d,{operation,expected:before.cursor,...fields})}
const refresh=d=>op(d,'refresh',{effect_id:'C'}),select=(d,effect_id)=>op(d,'select',{effect_id});
function active(d,operation,extra={}){return op(d,operation,{attempt_id:inspect(d).lifecycle.active,...extra})}
function setup(name,extra={}){const d=join(root,name);fs.mkdirSync(d);fs.mkdirSync(join(d,'source'));command('git',['-C',join(d,'source'),'init','-q']);command('git',['-C',join(d,'source'),'config','user.name','Fixture']);command('git',['-C',join(d,'source'),'config','user.email','fixture@example.invalid']);fs.writeFileSync(join(d,'source','tracked'),'original\n');command('git',['-C',join(d,'source'),'add','tracked']);command('git',['-C',join(d,'source'),'commit','-qm','initial']);
 const now=Math.floor(Date.now()/1000);const intents=['A','B','C','D'].map(id=>({operation:'create',target_sha256:hash(d+'/sink.db'),scope_sha256:hash('scope'),key_sha256:hash(id),request_sha256:hash('request-'+id),precondition_sha256:hash('empty'),valid_from:now-10,valid_until:now+3500}));
 write(join(d,'host.json'),{family:'sqlite',intents,...extra});write(join(d,'eval-config.json'),{suite:'exact-parent-artifact'});assert.equal(JSON.parse(command(kujo,['run',fixture,d,'init'])).ok,true);return d}
function state(d){return JSON.parse(fs.readFileSync(join(read(join(d,'pointer.json')).run_dir,'state.json'),'utf8').split('\n').slice(1).join('\n'))}
function decision(d){const s=state(d);return {schema:'kujo.intervention-decision/v2',decision_id:'finalize-'+s.revision,request_id:s.human_intervention.request_id,boundary_id:s.current_control_boundary.boundary_id,expected_state_revision:s.revision,action:'approve_override',reason:'Accept independently verified parent facts',decided_at:new Date().toISOString(),actor:{id:'local-operator',type:'human',authenticated_by:'installed-local-host',authorization:'parent-finalization'}}}
function assess(d,review=decision(d)){return run(d,{operation:'parent-inspect',decision:review})}
function eligible(d){const review=decision(d),a=assess(d,review);assert.equal(a.ok,true,JSON.stringify(a));assert.equal(a.status,'eligible');return {operation:'finalize',candidate:a.candidate,decision:review}}
function complete(d){assert.equal(refresh(d).ok,true);for(const effect of ['C','D']){assert.equal(select(d,effect).ok,true);assert.equal(active(d,'admit').ok,true);assert.equal(refresh(d).ok,true)}}
function prepared(name){const d=setup(name);complete(d);return d}
function truth(d){return Number(command('sqlite3',[join(d,'sink.db'),'SELECT count(*) FROM mutation_audit;']))}
const proofs=[];function proof(name){proofs.push(name);console.error('PASS '+name)}
const d=setup('prerequisites'),original=fs.readFileSync(join(d,'workcell/preservation.json'),'utf8');
assert.equal(state(d).steps[0].status,'paused');assert.equal(refresh(d).ok,true);assert.equal(assess(d).ok,false);proof('pending effects block parent');
assert.equal(select(d,'C').ok,true);assert.equal(active(d,'cancel',{reason:'operator_cancelled'}).ok,true);assert.equal(assess(d).ok,false);proof('cancelled required selection is not completion');
complete(d);assert.equal(truth(d),4);assert.equal(assess(d,null).ok,false);proof('unresolved operator review blocks');
const req=eligible(d);assert.equal(fs.readFileSync(join(d,'workcell/preservation.json'),'utf8'),original);proof('real Workcell refs and original bytes preserved');
function mutateHost(name,change){const p=join(d,'host.json'),raw=fs.readFileSync(p,'utf8'),v=JSON.parse(raw);change(v);write(p,v);assert.equal(run(d,req).ok,false,name);fs.writeFileSync(p,raw);proof(name)}
mutateHost('stale authority',v=>v.status='revoked');mutateHost('changed registration',v=>v.effect_set.registration.revision='2');mutateHost('wrong environment',v=>v.effect_set.environment_ref='sha256:'+hash('other'));mutateHost('operator authorization revoked',v=>v.operator_enabled=false);
mutateHost('stale evaluation',v=>{const e=JSON.parse(v.evaluation_raw);e.input_evidence_ids[0]='sha256:'+hash('old');v.evaluation_raw=JSON.stringify(e)});
mutateHost('wrong evaluation subject',v=>{const e=JSON.parse(v.evaluation_raw);e.subject.run_id='other';v.evaluation_raw=JSON.stringify(e)});
for(const file of ['output.txt','output-evidence.json','workcell/receipt.json']){const p=join(d,file),raw=fs.readFileSync(p);fs.rmSync(p);assert.equal(run(d,req).ok,false,'missing '+file);fs.writeFileSync(p,raw);fs.appendFileSync(p,'changed');assert.equal(run(d,req).ok,false,'changed '+file);fs.writeFileSync(p,raw);proof('missing/replaced '+file)}
const host=read(join(d,'host.json'));const workspace=host.workspace.workspace_path;
fs.renameSync(workspace,workspace+'.held');assert.equal(run(d,req).ok,false);fs.renameSync(workspace+'.held',workspace);proof('retained workspace missing');
command('git',['-C',workspace,'commit','--allow-empty','-qm','changed-target']);assert.equal(run(d,req).ok,false);command('git',['-C',workspace,'reset','--hard',host.workspace.source_commit]);proof('changed retained Git HEAD');
const statePath=join(read(join(d,'pointer.json')).run_dir,'state.json'),stateRaw=fs.readFileSync(statePath,'utf8');
for(const [name,change] of Object.entries({'stale run revision':s=>s.revision++,'new unresolved child':s=>s.steps.push({...s.steps[0],id:'child',status:'pending',depends_on:['action']}),'expired preservation':s=>s.current_control_boundary.preservation.retain_until='2000-01-01T00:00:00Z'})){const s=state(d);change(s);fs.writeFileSync(statePath,'DISPATCH_ASSURANCE_STATE_V1BETA1\n'+JSON.stringify(s));assert.equal(run(d,req).ok,false,name);fs.writeFileSync(statePath,stateRaw);proof(name)}
command('sqlite3',[join(d,'sink.db'),"UPDATE logical_effects SET request='changed' WHERE rowid=(SELECT max(rowid) FROM logical_effects);"]);assert.equal(assess(d).ok,false);proof('independent sink uncertainty blocks');
const happy=prepared('success');const staleChild=eligible(happy);assert.equal(refresh(happy).ok,true);assert.equal(run(happy,staleChild).ok,false);proof('legitimate new assessment invalidates candidate');
const request=eligible(happy);assert.equal(run(happy,{operation:'generic-review',decision:request.decision}).ok,false);proof('generic approved review cannot bypass finalization');assert.equal(run(happy,request).ok,true);assert.equal(state(happy).status,'completed');assert.equal(run(happy,request).ok,false);assert.equal(assess(happy,null).status,'already_finalized');assert.equal(truth(happy),4);assert.equal(inspect(happy).ok,true);proof('separate finalization without effect replay');
const fail=prepared('evaluation-fail');const fc=read(join(fail,'host.json')),evaluation=JSON.parse(fc.evaluation_raw);evaluation.verdict='fail';evaluation.severity='error';evaluation.checks={passed:0,failed:1,warned:0,skipped:0};fc.evaluation_raw=JSON.stringify(evaluation);write(join(fail,'host.json'),fc);const failedReq=eligible(fail);assert.equal(failedReq.candidate.outcome,'failed');assert.equal(run(fail,failedReq).ok,true);assert.equal(state(fail).status,'failed');proof('Eval fail maps through existing policy');
async function killAt(d,request,point,cwd=process.cwd()){const p=spawn(kujo,['run',fixture,d,point,requestFile(d,request)],{cwd,env,stdio:['ignore','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),120000);p.stdout.on('data',b=>{out+=b;if(out.includes('CRASH:'+point))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);const status=await new Promise(r=>p.on('exit',(code,signal)=>r({code,signal})));clearTimeout(timer);assert.ok(out.includes('CRASH:'+point),out+err);assert.equal(status.signal,'SIGKILL');assert.equal(err,'')}
const crash=prepared('before');const before=eligible(crash);await killAt(crash,before,'before_finalization');assert.equal(state(crash).status,'paused');assert.equal(run(crash,{operation:'recovery-plan'}).assessment.classification,'consistent');assert.equal(run(crash,before).ok,true);proof('SIGKILL before decision remains nonterminal');
const reply=prepared('reply');const replyReq=eligible(reply);await killAt(reply,replyReq,'after_finalization');assert.equal(state(reply).status,'completed');assert.equal(assess(reply,null).status,'already_finalized');assert.equal(run(reply,replyReq).ok,false);assert.equal(truth(reply),4);proof('SIGKILL after terminal reply loss is final');
const race=prepared('race'),raceReq=eligible(race);let ready=0;const results=await Promise.all([1,2].map(()=>new Promise((resolve,reject)=>{let out='',err='',announced=false;const p=spawn(kujo,['run',fixture,race,'race',requestFile(race,raceReq)],{env,stdio:['ignore','pipe','pipe']});const timer=setTimeout(()=>p.kill('SIGKILL'),120000);p.stdout.on('data',b=>{out+=b;if(!announced&&out.includes('READY')){announced=true;if(++ready===2)fs.writeFileSync(join(race,'race-release'),'go')}});p.stderr.on('data',b=>err+=b);p.on('exit',code=>{clearTimeout(timer);try{assert.equal(code,0,out+err);assert.equal(err,'');resolve(JSON.parse(out.trim().split('\n').at(-1)))}catch(e){reject(e)}})})));assert.equal(results.filter(r=>r.ok).length,1);assert.equal(truth(race),4);assert.equal(assess(race,null).status,'already_finalized');assert.equal(run(race,raceReq).ok,false);const raceJournal=fs.readFileSync(join(read(join(race,'pointer.json')).run_dir,'control-events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(raceJournal.filter(e=>e.kind==='parent_finalized').length,1);proof('two independently assessed fresh controllers one durable finalization');
const successReport=setup('producer-success',{reported_status:'success'});assert.equal(state(successReport).status,'paused');assert.equal(state(successReport).steps[0].status,'paused');proof('producer success still requires parent finalization');
const descendant=setup('real-descendant',{descendant:true});complete(descendant);assert.equal(assess(descendant).ok,false);assert.equal(state(descendant).steps[1].status,'pending');proof('anchored required descendant blocks terminal transition');
const revoked=prepared('revoked-at-boundary');assert.equal(run(revoked,eligible(revoked),'revoke-finalization').ok,false);assert.equal(state(revoked).status,'paused');proof('live authority revoked inside finalization boundary');
// Disposable source-copy fault injector: actual kill after immutable event fsync,
// before index append. The source pin is negotiated after injection.
const copy=join(root,'source-copy');fs.mkdirSync(copy);for(const name of ['src','tests'])fs.cpSync(resolve(name),join(copy,name),{recursive:true,filter:p=>!p.includes('/tests/tmp')});
for(const sibling of ['workcell','eval'])fs.symlinkSync(resolve('..',sibling),join(root,sibling),'dir');
const journal=join(copy,'src/core/control_journal.kujo');fs.writeFileSync(journal,fs.readFileSync(journal,'utf8').replace('    append_file(path, line)','    if kind == "parent_finalized" {print("CRASH:orphan");sleep(30000)}\n    append_file(path, line)'));
// Setup and ordinary sequence in isolated source tree with its own negotiated pin.
const originalCwd=process.cwd();process.chdir(copy);const orphan=prepared('orphan');const orphanReq=eligible(orphan);await killAt(orphan,orphanReq,'orphan',copy);assert.equal(state(orphan).status,'paused');const plan=run(orphan,{operation:'recovery-plan'});assert.equal(plan.ok,true,JSON.stringify(plan));assert.equal(plan.assessment.classification,'reconcilable',JSON.stringify(plan));assert.equal(run(orphan,{operation:'recovery-apply',plan:plan.plan}).ok,true);assert.equal(state(orphan).status,'completed');assert.equal(assess(orphan,null).status,'already_finalized');assert.equal(truth(orphan),4);process.chdir(originalCwd);proof('orphan durable finalization recovered by fresh controllers');
console.log(JSON.stringify({ok:true,root,checks:proofs.length,proofs}));
