// Maintenance harness: execution, verification and admission use real Kujo paths.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const cwd=process.cwd(), runtime=process.env.KUJO_BIN||'/tmp/kujo-wave-a-release-candidate-bin';
const root=path.resolve('tests/tmp/persisted-negotiation-'+Date.now());fs.mkdirSync(root,{recursive:true});
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'), write=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v)), read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const env={...process.env,DISPATCH_OFFLINE_FIXTURE:'true',DISPATCH_ALLOW_ANY_OUTPUT_ROOT:'true',DISPATCH_BUNDLE_SIGNING_KEY:crypto.randomBytes(32).toString('hex')};
function command(exe,args,opts={}){const r=spawnSync(exe,args,{cwd,env,encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024,...opts});assert.equal(r.status,0,r.stdout+'\n'+r.stderr);assert.equal(r.stderr,'');return r.stdout.trim();}
const run=(dir,phase)=>JSON.parse(command(runtime,['run','tests/persisted_negotiation_fixture.kujo',dir,phase]));
function setup(name,extra={}){const dir=path.join(root,name);fs.mkdirSync(dir);const now=Math.floor(Date.now()/1000);const config={runtime,cwd,entry:'examples/effect-assurance/sqlite-adapter.kujo',issuer:'sqlite-local',db:path.join(dir,'sink.sqlite'),boundary:'after_commit',effect_class:'external_idempotent',intent:{operation:'create',target_sha256:sha('target'),scope_sha256:sha(dir),key_sha256:sha('fixture-key'),request_sha256:sha('PRIVATE_PAYLOAD_CANARY_7x'),precondition_sha256:sha('empty'),valid_from:now-5,valid_until:now+(extra.validity_seconds||1800)},...extra};write(path.join(dir,'config.json'),config);command(runtime,['run',config.entry,dir,'init']);const revisions=run(dir,'install');const started=run(dir,'start');assert.equal(started.ok,true,JSON.stringify(started));return {dir,revisions};}
const guarded='DISPATCH_ASSURANCE_STATE_V1ALPHA1\n';const statePath=dir=>path.join(read(path.join(dir,'state-pointer.json')).run_dir,'state.json');const state=dir=>JSON.parse(fs.readFileSync(statePath(dir),'utf8').slice(guarded.length));
const proofs=[];
const {dir,revisions}=setup('required-restart');const original=state(dir);assert.equal(original.assurance_negotiation.mode,'required');assert.equal(run(dir,'generic').code,'assurance_controller_incompatible');assert.equal(run(dir,'resume').code,'compat_assurance_absent');assert.equal(run(dir,'assure').ok,true);const cp=run(dir,'checkpoint');assert.equal(cp.ok,true);write(path.join(dir,'checkpoint-id'),cp.checkpoint.checkpoint_id);
let store=read(path.join(dir,'operator-store.json'));store.selected='legacy';write(path.join(dir,'operator-store.json'),store);const resumed=run(dir,'resume');assert.equal(resumed.ok,true);assert.equal(resumed.policy.config_revision,revisions.r1);proofs.push({scenario:'required-fresh-controller-weaker-default',ok:true,revision:revisions.r1});
const code=x=>x.code||x.error?.code;
function denyCheck(t,expected){const p=state(t.dir).assurance_negotiation;const answer=run(t.dir,'resume');assert.equal(answer.ok,false,JSON.stringify(answer));if(expected)assert.equal(code(answer),expected);assert.deepEqual(state(t.dir).assurance_negotiation,p);proofs.push({scenario:path.basename(t.dir),code:code(answer)});}
for(const kind of ['missing','revoked','substituted','changed-verifier','implementation-replaced']){const t=setup('revision-'+kind);assert.equal(run(t.dir,'assure').ok,true);const file=path.join(t.dir,'operator-store.json'),op=read(file);op.selected=t.revisions.r2;if(kind==='missing')delete op.revisions[t.revisions.r1];if(kind==='revoked')op.revisions[t.revisions.r1].status='revoked';if(kind==='substituted')op.revisions[t.revisions.r1]=op.revisions[t.revisions.r2];if(kind==='changed-verifier')op.revisions[t.revisions.r1].descriptor.verifier_sha256=sha('different implementation');if(kind==='implementation-replaced'){write(path.join(t.dir,'replacement.kujo'),'func verify() { return false }');op.revisions[t.revisions.r1].implementation=[{root:t.dir,path:'replacement.kujo'}];}write(file,op);denyCheck(t,{missing:'assurance_policy_revision_missing',revoked:'assurance_policy_revision_revoked',substituted:'assurance_configuration_mismatch','changed-verifier':'assurance_configuration_mismatch','implementation-replaced':'assurance_verifier_revision_mismatch'}[kind]);}
for(const kind of ['absent','unknown-profile','unknown-envelope','invalid-selected','deleted-selected','expired','revoked-selected']){const t=setup('optional-'+kind,{mode:'optional',fallback:'legacy_unavailable',...(kind==='unknown-profile'?{profile:'future.profile'}:{}),...(kind==='expired'?{validity_seconds:12}:{})});if(!['absent','unknown-profile'].includes(kind))assert.equal(run(t.dir,kind==='unknown-envelope'?'assure-future':kind==='invalid-selected'?'assure-invalid':'assure').ok,true);if(kind==='invalid-selected'||kind==='deleted-selected'){const selected=state(t.dir).assurance_selection;const f=path.join(path.dirname(statePath(t.dir)),selected.sidecar_ref);if(kind==='deleted-selected')fs.unlinkSync(f);denyCheck(t,kind==='deleted-selected'?'assurance_selected_evidence_unavailable':undefined);}else if(kind==='expired'){const selected=state(t.dir).assurance_selection;const f=path.join(path.dirname(statePath(t.dir)),selected.sidecar_ref);const doc=read(f);const cp=run(t.dir,'checkpoint');assert.equal(cp.ok,true);write(path.join(t.dir,'checkpoint-id'),cp.checkpoint.checkpoint_id);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,Math.max(0,doc.valid_until*1000-Date.now()+100));denyCheck(t,'assurance_expired_or_future');}else if(kind==='revoked-selected'){const op=read(path.join(t.dir,'operator-store.json'));op.revisions[t.revisions.r1].status='revoked';write(path.join(t.dir,'operator-store.json'),op);denyCheck(t,'assurance_policy_revision_revoked');}else{const answer=run(t.dir,'resume');assert.equal(answer.ok,true,JSON.stringify(answer));proofs.push({scenario:'optional-'+kind,ok:true});}}
for(const kind of ['revoke','expire']){const t=setup('delayed-'+kind,{...(kind==='expire'?{validity_seconds:30}:{})});assert.equal(run(t.dir,'assure').ok,true);const before=fs.readFileSync(path.join(t.dir,'action-invocations'),'utf8');const denied=run(t.dir,'resume-'+kind+'-hook');assert.equal(code(denied),kind==='revoke'?'assurance_policy_revision_revoked':'assurance_expired_or_future');assert.equal(fs.readFileSync(path.join(t.dir,'action-invocations'),'utf8'),before);assert.equal(state(t.dir).steps[0].status,'running');assert.equal(code(run(t.dir,'execute-existing')),kind==='revoke'?'assurance_policy_revision_revoked':'assurance_expired_or_future');assert.equal(fs.readFileSync(path.join(t.dir,'action-invocations'),'utf8'),before);proofs.push({scenario:'delayed-'+kind+'-before-action-and-running-restart',blocked:true});}
const optionalDeny=setup('optional-deny',{mode:'optional',fallback:'deny'});denyCheck(optionalDeny,'compat_assurance_absent');
const oversized=setup('oversized-association');const associationBefore=fs.readFileSync(statePath(oversized.dir),'utf8');assert.equal(code(run(oversized.dir,'assure-oversized-subject')),'assurance_selection_invalid');assert.equal(fs.readFileSync(statePath(oversized.dir),'utf8'),associationBefore);proofs.push({scenario:'oversized-association-no-authority-mutation',blocked:true});
const tamper=setup('policy-tampered');const originalBytes=fs.readFileSync(statePath(tamper.dir),'utf8');const bad=state(tamper.dir);bad.assurance_negotiation.mode='legacy';write(statePath(tamper.dir),guarded+JSON.stringify(bad));assert.equal(run(tamper.dir,'load').ok,false);write(statePath(tamper.dir),originalBytes);const forged=state(tamper.dir);const legacy={schema:'dispatch.assurance-negotiation/v1alpha1',mode:'legacy',fallback:'deny',profile:'',profile_version:'',config_revision:''};legacy.policy_sha256=sha(JSON.stringify(Object.fromEntries(Object.keys(legacy).sort().map(k=>[k,legacy[k]]))));forged.assurance_negotiation=legacy;delete forged.required_features;delete forged.assurance_store;write(statePath(tamper.dir),forged);assert.equal(code(run(tamper.dir,'load')),'assurance_policy_tampered');write(statePath(tamper.dir),originalBytes);proofs.push({scenario:'manual-policy-tamper',blocked:true});
const stale=setup('stale-checkpoint');const old=run(stale.dir,'checkpoint');assert.equal(old.ok,true);assert.equal(run(stale.dir,'assure').ok,true);write(path.join(stale.dir,'checkpoint-id'),old.checkpoint.checkpoint_id);denyCheck(stale,'stale_checkpoint');
const lost=setup('selection-removed');assert.equal(run(lost.dir,'assure').ok,true);const lostState=state(lost.dir);delete lostState.assurance_selection;write(statePath(lost.dir),guarded+JSON.stringify(lostState));denyCheck(lost,'assurance_journal_state_mismatch');
// Retained R1 is authoritative even when R2 is now selected for new runs.
const retained=setup('retained-revision');assert.equal(run(retained.dir,'assure').ok,true);const retainedPath=statePath(retained.dir);let retainedStore=read(path.join(retained.dir,'operator-store.json'));retainedStore.selected=retained.revisions.r2;write(path.join(retained.dir,'operator-store.json'),retainedStore);assert.equal(run(retained.dir,'resume').policy.config_revision,retained.revisions.r1);assert.equal(run(retained.dir,'start').policy.config_revision,retained.revisions.r2);assert.equal(JSON.parse(fs.readFileSync(retainedPath,'utf8').slice(guarded.length)).assurance_negotiation.config_revision,retained.revisions.r1);proofs.push({scenario:'retained-r1-and-new-r2',ok:true});
const rollback=setup('state-rollback');const saved=fs.readFileSync(statePath(rollback.dir),'utf8');assert.equal(run(rollback.dir,'assure').ok,true);write(statePath(rollback.dir),saved);denyCheck(rollback,'control_recovery_required');
// SQLite remains authoritative after environment/default changes.
env.DISPATCH_STATE_BACKEND='sqlite';const database=setup('sqlite-authority');assert.equal(run(database.dir,'assure').ok,true);delete env.DISPATCH_STATE_BACKEND;const dbPolicy=state(database.dir).assurance_negotiation;write(statePath(database.dir),'{}');assert.deepEqual(run(database.dir,'load').policy,dbPolicy);assert.equal(run(database.dir,'export').ok,true);assert.ok(read(path.join(database.dir,'bundle.json')).artifacts.state_json.startsWith(guarded));assert.equal(run(database.dir,'resume').ok,true);const dbFile=path.join(database.dir,'runs/.dispatch/state.db');fs.renameSync(dbFile,dbFile+'.held');assert.equal(code(run(database.dir,'load')),'assurance_authoritative_store_missing');fs.renameSync(dbFile+'.held',dbFile);proofs.push({scenario:'sqlite-authority-over-stale-json-and-weaker-backend',ok:true});
// Existing bundles preserve protected bytes, but lack the complete journal/evidence.
const bundle=setup('bundle-policy');assert.equal(run(bundle.dir,'assure').ok,true);assert.equal(run(bundle.dir,'export').ok,true);assert.equal(code(run(bundle.dir,'import-existing')),'assurance_import_identity_conflict');const imported=run(bundle.dir,'import');assert.equal(imported.ok,true,JSON.stringify(imported));const importedBytes=fs.readFileSync(path.join(imported.run_dir,'state.json'),'utf8');assert.deepEqual(JSON.parse(importedBytes.slice(guarded.length)).assurance_negotiation,state(bundle.dir).assurance_negotiation);write(path.join(bundle.dir,'state-pointer.json'),{run_id:imported.run_id,run_dir:imported.run_dir});assert.equal(run(bundle.dir,'import-load').ok,false);proofs.push({scenario:'bundle-preserves-policy-without-claiming-portable-recovery',ok:true});
// Run the actual previous source reader, not a mock capability flag.
const older=path.join(root,'older-controller');fs.mkdirSync(older);const archived=spawnSync('git',['archive','63d8097'],{cwd,maxBuffer:32*1024*1024});assert.equal(archived.status,0);const unpack=spawnSync('tar',['-x','-C',older],{input:archived.stdout});assert.equal(unpack.status,0);write(path.join(older,'old-probe.kujo'),'from src.core.state import load_run_state\narguments := args()\ntry {loaded := load_run_state(arguments[0], arguments[1]); print(to_json({"accepted": loaded["ok"]}))} except err {print(to_json({"accepted": false}))}\n');
for(const target of [stale,bundle,database]){let ptr=read(path.join(target.dir,'state-pointer.json'));const before=fs.readFileSync(path.join(ptr.run_dir,'state.json'),'utf8');const checked=JSON.parse(command(runtime,['run','old-probe.kujo',path.dirname(ptr.run_dir),ptr.run_id],{cwd:older,env:{...env,...(target===database?{DISPATCH_STATE_BACKEND:'sqlite'}:{})}}));assert.equal(checked.accepted,false);assert.equal(fs.readFileSync(path.join(ptr.run_dir,'state.json'),'utf8'),before);}proofs.push({scenario:'actual-63d8097-controller-refuses-protected-filesystem-sqlite-and-import',ok:true});
write(path.join(root,'proof.json'),proofs);console.log(JSON.stringify({root,proofs}));
