import {setup,program,evaluator,policy,resourceOptions,run,finishProgram,sealEval,rop,rapply,report,evalRow,subject,state,assert,patch,join,write,fs,spawnSync,kujo,resolve,env,command,gop,root} from './resource_helpers.mjs';
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)};
const d=setup('eval-budget',[program('A'),{...evaluator('E','A'),max_eval_attempts:2},evaluator('F','A')],resourceOptions(policy([],[],1),2));
run(d,'drive');finishProgram(d,'A');run(d,'drive');
// Binding is informational: an externally produced Eval file cannot bypass dispatch.
run(d,'evaluate','E');assert.equal(gop(d,'node-assess',{node_id:'E'}).ok,false);
const planned=rop(d,'reserve',{nodes:['E']});assert.equal(planned.ok,true);const configPath=join(d,'E/eval-config.json'), configBytes=fs.readFileSync(configPath);fs.writeFileSync(configPath,'{"changed":true}');assert.equal(rop(d,'reserve',{nodes:['E']}).ok,false);fs.writeFileSync(configPath,configBytes);
const revoked=rop(d,'reserve',{nodes:['E'],candidate:planned.candidate,actor:{id:'local-operator',type:'human',authenticated_by:'installed-local-host',authorization:'graph-finalization'}},'apply',{GRAPH_REVOKE:'before_resource'});assert.equal(revoked.ok,false);assert.equal(report(d).report.evaluations.reserved,0);patch(join(d,'host.json'),c=>c.operator_enabled=true);
rapply(d,'reserve',{nodes:['E']});assert.equal(report(d).report.evaluations.reserved,1);assert.equal(fs.existsSync(join(d,'E/eval-executions.log')),false);pass('Eval output and reservation do not authorize terminal completion or execution');
patch(join(d,'E/host.json'),c=>c.infrastructure_fail=true);rapply(d,'dispatch',{node_id:'E'});assert.equal(evalRow(d,'E').resolution.candidate.outcome,'infrastructure_failed');assert.equal(rop(d,'release',{node_id:'E'}).ok,false);const first=evalRow(d,'E');
patch(join(d,'E/host.json'),c=>c.infrastructure_fail=false);rapply(d,'reserve',{nodes:['E']});assert.notEqual(evalRow(d,'E').attempt_id,first.attempt_id);assert.equal(evalRow(d,'E').binding_ref,first.binding_ref);rapply(d,'dispatch',{node_id:'E'});sealEval(d,'E');assert.equal(state(d).eval_attempts.E.length,2);assert.equal(fs.readFileSync(join(d,'A/executions.log'),'utf8').trim().split('\n').length,1);pass('terminated evaluator infrastructure failure retries exact result with a new Eval identity without rerunning program');
run(d,'drive');assert.equal(rop(d,'reserve',{nodes:['F']}).ok,false);assert.equal(report(d).report.evaluations.consumed,2);assert.equal(report(d).report.evaluations.available,0);assert.equal(gop(d,'graph-assess').candidate.outcome,'blocked');assert.equal(fs.existsSync(join(d,'F/eval-executions.log')),false);pass('Eval exhaustion denies new work but permits consumed Eval finalization; required remainder stays blocked');
const e=subject(d,'E');rapply(d,'observe',{subject:e,source_kind:'runtime'});const runtime=report(d).report.readings.find(r=>r.subject.attempt_id===e.attempt_id&&r.source_kind==='runtime');assert.equal(runtime.facts.class,'observed');assert.ok(runtime.facts.wall_ns>0);assert.equal(runtime.facts.hard_policy_eligible,false);pass('real isolated evaluator runtime report retained with process scope and exact digest');
const generated=spawnSync(kujo,['run',resolve('tests/resource_model_fixture.kujo')],{cwd:resolve('../agents-sdk'),env:{...env,KUJO_MODULE_PATH:resolve('../agents-sdk')},encoding:'utf8'});assert.equal(generated.status,0,generated.stdout+generated.stderr);const model=JSON.parse(generated.stdout);write(join(d,'E',`resource-${e.attempt_id}-model.json`),model);rapply(d,'observe',{subject:e,source_kind:'model'});const usage=report(d).report.readings.find(r=>r.subject.attempt_id===e.attempt_id&&r.source_kind==='model');assert.equal(usage.facts.reported.input_tokens,41);assert.equal(usage.facts.reported.output_tokens,7);assert.equal(usage.facts.estimated.class,'estimated');assert.ok(usage.facts.estimated.component_tokens>0);assert.equal(report(d).report.monetary_cost.value,null);assert.ok(report(d).report.totals.reported_input_tokens.unknown_attempts>0);assert.equal(report(d).report.totals.reported_input_tokens.total,null);pass('actual SDK context-ledger projection keeps offline reported fixture, estimates and unknown attempt coverage separate');
assert.equal(rop(d,'observe',{subject:e,source_kind:'model'}).ok,false);const fact=state(d).resource_sources;assert.ok(Object.keys(fact).length===2);const runtimeFile=join(state(d).run_dir,'node-input',runtime.source_ref.slice(7)+'.raw');const before=fs.readFileSync(runtimeFile);fs.writeFileSync(runtimeFile,'corrupt');assert.equal(report(d).ok,false);fs.writeFileSync(runtimeFile,before);assert.equal(report(d).ok,true);pass('duplicate accounting cannot add usage twice; corrupt retained measurement fails closed');
console.log(JSON.stringify({ok:true,checks:proofs.length,proofs,root}));
