import fs from 'node:fs';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawn,spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const kujo=process.env.KUJO_BIN||'kujo',root=fs.mkdtempSync(join(tmpdir(),'sequential-effects-'));
const hash=x=>createHash('sha256').update(x).digest('hex'), read=p=>JSON.parse(fs.readFileSync(p,'utf8')),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v));
const env={...process.env,KUJO_MODULE_PATH:resolve('..'),DISPATCH_OFFLINE_FIXTURE:'true',DISPATCH_ALLOW_ANY_OUTPUT_ROOT:'true'};
function command(program,args,input){const p=spawnSync(program,args,{encoding:'utf8',input,timeout:60000,env,maxBuffer:8*1024*1024});assert.equal(p.status,0,p.stdout+p.stderr);assert.equal(p.stderr,'');return p.stdout.trim()}
const snapshots=new Map();
let serial=0;const requestFile=(d,r)=>{const p=join(d,'request-'+serial+++'.json');write(p,r);return p};
function run(d,r,mode='operate'){const result=JSON.parse(command(kujo,['run','tests/sequential_effect_fixture.kujo',d,mode,requestFile(d,r)]));if(result.ok)snapshots.set(d,result);else snapshots.delete(d);return result}
const inspect=d=>run(d,{operation:'inspect'});
function op(d,operation,fields={},mode='operate'){const before=snapshots.get(d)||inspect(d);assert.equal(before.ok,true,JSON.stringify(before));return run(d,{operation,expected:before.cursor,...fields},mode)}
const refresh=d=>op(d,'refresh',{effect_id:'C'}),select=(d,id='C')=>op(d,'select',{effect_id:id});
function active(d,operation,extra={},mode='operate'){return op(d,operation,{attempt_id:(snapshots.get(d)||inspect(d)).lifecycle.active,...extra},mode)}
function git(d,args,input){return command('git',['--git-dir='+join(d,'sink.git'),...args],input)}
function setup(family,name,extra={}){const d=join(root,family+'-'+name);fs.mkdirSync(d);let old='',next='';if(family==='git'){command('git',['init','--bare','--quiet',join(d,'sink.git')]);old=git(d,['hash-object','-w','--stdin'],'old');next=git(d,['hash-object','-w','--stdin'],'new')}
 const now=Math.floor(Date.now()/1000);const intents=['A','B','C','D'].map(id=>({operation:family==='git'?'update':'create',target_sha256:hash(d+(family==='git'?'/sink.git:'+id:'/sink.db')),scope_sha256:hash('scope'),key_sha256:hash(id),request_sha256:hash(family==='git'?next:'request-'+id),precondition_sha256:hash(family==='git'?old:'empty'),valid_from:now-10,valid_until:now+3500}));
 write(join(d,'host.json'),{family,old_oid:old,new_oid:next,intents,...extra});if(family==='git')for(const intent of intents)git(d,['update-ref','refs/kujo-targets/'+intent.target_sha256,old]);assert.equal(JSON.parse(command(kujo,['run','tests/sequential_effect_fixture.kujo',d,'init'])).ok,true);return d}
const proofs=[];
const families=process.env.SEQUENTIAL_FAMILY?[process.env.SEQUENTIAL_FAMILY]:['sqlite','git'];
if(!process.env.SEQUENTIAL_FAMILY&&!process.env.SEQUENTIAL_ADMISSION_ONLY){
 const results=await Promise.all(families.map(family=>new Promise((resolve,reject)=>{
  const child=spawn(process.execPath,[new URL(import.meta.url).pathname],{env:{...process.env,SEQUENTIAL_FAMILY:family},stdio:['ignore','pipe','pipe']});let out='',err='';
  child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);
  child.on('error',reject);child.on('exit',code=>{try{assert.equal(code,0,out+err);assert.equal(err,'');resolve(JSON.parse(out))}catch(error){reject(error)}});
 })));
 console.log(JSON.stringify({ok:true,roots:results.map(r=>r.root),checks:results.reduce((n,r)=>n+r.checks,0),proofs:results.flatMap(r=>r.proofs)}));process.exit(0);
}
for(const family of (process.env.SEQUENTIAL_ADMISSION_ONLY?[]:families)){
 const d=setup(family,'valid');assert.equal(refresh(d).ok,true,'refresh '+family);const c=select(d);assert.equal(c.ok,true,'select '+JSON.stringify(c));assert.equal(active(d,'admit').ok,true,'admit '+family);assert.equal(select(d,'D').ok,false,'needs new assessment');assert.equal(refresh(d).ok,true);const next=select(d,'D');assert.equal(next.ok,true,'select D '+JSON.stringify(next));assert.notEqual(next.lifecycle.active,c.lifecycle.active);assert.equal(active(d,'admit').ok,true,'admit D');assert.equal(active(d,'admit').ok,false);assert.equal(active(d,'cancel',{reason:'operator_cancelled'}).ok,false);assert.equal(active(d,'rebind').ok,false);proofs.push(family+'-independent-C-D-lifecycles');
}
function alter(d,change){const p=join(d,'host.json'),v=read(p);change(v);write(p,v)}
function truth(d){const cfg=read(join(d,'host.json'));if(cfg.family==='git')return git(d,['for-each-ref','--format=%(refname)','refs/kujo-effects/']).split('\n').filter(Boolean).length;return Number(command('sqlite3',[join(d,'sink.db'),'SELECT count(*) FROM mutation_audit;']))}
function expectedRequest(d,operation,fields={}){return {operation,expected:inspect(d).cursor,...fields}}
async function killAt(d,request,point){snapshots.delete(d);const p=spawn(kujo,['run','tests/sequential_effect_fixture.kujo',d,point,requestFile(d,request)],{env,stdio:['ignore','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),60000);p.stdout.on('data',b=>{out+=b;if(out.includes('CRASH:'+point))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);const status=await new Promise(r=>p.on('exit',(code,signal)=>r({code,signal})));clearTimeout(timer);assert.ok(out.includes('CRASH:'+point),out+err);assert.equal(status.signal,'SIGKILL');assert.equal(err,'')}
async function race(d,requests){snapshots.delete(d);fs.rmSync(join(d,'race-release'),{force:true});let ready=0;return Promise.all(requests.map(request=>new Promise((resolve,reject)=>{let out='',err='',announced=false;const p=spawn(kujo,['run','tests/sequential_effect_fixture.kujo',d,'race',requestFile(d,request)],{env,stdio:['ignore','pipe','pipe']});const timer=setTimeout(()=>p.kill('SIGKILL'),60000);p.stdout.on('data',b=>{out+=b;if(!announced&&out.includes('READY')){announced=true;if(++ready===requests.length)fs.writeFileSync(join(d,'race-release'),'go')}});p.stderr.on('data',b=>err+=b);p.on('exit',code=>{clearTimeout(timer);try{assert.equal(code,0,out+err);assert.equal(err,'');resolve(JSON.parse(out.trim().split('\n').at(-1)))}catch(e){reject(e)}})})))}
function prepared(family,name,extra={}){const d=setup(family,name,extra);assert.equal(refresh(d).ok,true);assert.equal(select(d).ok,true);return d}
const pause=ms=>new Promise(r=>setTimeout(r,ms));
for(const family of (process.env.SEQUENTIAL_ADMISSION_ONLY?[]:families)){
 const d=prepared(family,'renew',{evidence_seconds:12}),before=inspect(d),original=before.lifecycle.attempts[before.lifecycle.active].selection;
 await pause(12100);assert.equal(active(d,'admit').ok,false);alter(d,c=>c.evidence_seconds=300);assert.equal(refresh(d).ok,true);assert.equal(active(d,'admit').ok,false,'renewal alone grants no authority');const rebound=active(d,'rebind');assert.equal(rebound.ok,true);assert.deepEqual(rebound.lifecycle.attempts[rebound.lifecycle.active].selection,original);assert.equal(rebound.lifecycle.attempts[rebound.lifecycle.active].rebindings.length,1);assert.equal(active(d,'admit').ok,true);assert.equal(truth(d),3);assert.equal(active(d,'rebind').ok,false);proofs.push(family+'-expiry-explicit-rebind-same-attempt');
 const cancelled=prepared(family,'cancel');const abandoned=inspect(cancelled).lifecycle.active;assert.equal(active(cancelled,'cancel',{reason:'operator_cancelled'}).ok,true);assert.equal(op(cancelled,'admit',{attempt_id:abandoned}).ok,false);assert.equal(truth(cancelled),2);assert.equal(refresh(cancelled).ok,true);const replacement=select(cancelled);assert.equal(replacement.ok,true);assert.notEqual(replacement.lifecycle.active,abandoned);assert.equal(active(cancelled,'admit').ok,true);proofs.push(family+'-cancel-retained-replacement-explicit');
 for(const point of ['after_admission','after_mutation','after_observation']){
  const x=prepared(family,point),v=inspect(x),req=expectedRequest(x,'admit',{attempt_id:v.lifecycle.active});await killAt(x,req,point);assert.equal(truth(x),point==='after_admission'?2:3);assert.equal(active(x,'admit').ok,false);assert.equal(active(x,'cancel',{reason:'operator_cancelled'}).ok,false);assert.equal(active(x,'rebind').ok,false);assert.equal(active(x,'verify').ok,true);
  if(point!=='after_admission'){assert.equal(select(x,'D').ok,false);assert.equal(refresh(x).ok,true);const q=expectedRequest(x,'select',{effect_id:'D'});const raced=await race(x,[q,q]);assert.equal(raced.filter(y=>y.ok).length,1);assert.equal(run(x,req).ok,false);assert.equal(active(x,'admit').ok,true);assert.equal(truth(x),4)}else{assert.equal(refresh(x).ok,true);assert.equal(select(x,'D').ok,false)}proofs.push(family+'-'+point+'-never-replay');
 }
 for(const pair of [['cancel','cancel'],['cancel','admit'],['rebind','cancel'],['rebind','rebind'],['rebind','admit']]){
  const x=prepared(family,'race-'+pair.join('-'));if(pair.includes('rebind')){await pause(1100);assert.equal(refresh(x).ok,true)}const v=inspect(x);const requests=pair.map(operation=>({operation,expected:v.cursor,attempt_id:v.lifecycle.active,...(operation==='cancel'?{reason:'no_longer_required'}:{})}));const results=await race(x,requests);assert.equal(results.filter(y=>y.ok).length,1,JSON.stringify(results));assert.ok(truth(x)<=3);assert.equal(run(x,requests[0]).ok,false);proofs.push(family+'-race-'+pair.join('-'));
 }
 for(const [operation,points] of [['rebind',['before_rebind','after_rebind']],['cancel',['before_cancel','after_cancel']],['select',['before_selection','after_selection']]]){
  for(const point of points){const x=prepared(family,'crash-'+point);if(operation==='rebind'){await pause(1100);assert.equal(refresh(x).ok,true)}if(operation==='select'){assert.equal(active(x,'admit').ok,true);assert.equal(refresh(x).ok,true)}const v=inspect(x),req={operation,expected:v.cursor,...(operation==='select'?{effect_id:'D'}:{attempt_id:v.lifecycle.active}),...(operation==='cancel'?{reason:'operator_cancelled'}:{})};await killAt(x,req,point);const reload=inspect(x);assert.equal(reload.ok,true);assert.equal(truth(x),operation==='select'?3:2);if(point.startsWith('before'))assert.equal(run(x,req).ok,true);else assert.equal(run(x,req).ok,false);if(operation==='select')assert.equal(active(x,'admit').ok,true);proofs.push(family+'-crash-'+point)}
 }
 for(const [name,change] of Object.entries({registration:c=>c.effect_set.registration.revision='2',plan:c=>c.effect_set.plan.effects[2].effect_id='X',target:c=>c.effect_set.sink_path+='.other',authority:c=>c.descriptor.authority_sha256=hash('other'),configuration:c=>c.descriptor.verifier_version='2',environment:c=>c.effect_set.environment_valid=false,preservation:c=>c.effect_set.plan.preserve_until=1})){
  const x=prepared(family,'invalid-'+name);await pause(1100);assert.equal(refresh(x).ok,true);alter(x,change);for(const operation of ['rebind','cancel','admit'])assert.equal(active(x,operation,operation==='cancel'?{reason:'operator_cancelled'}:{}).ok,false,name+' '+operation);assert.equal(truth(x),2);proofs.push(family+'-invalid-'+name)
 }
 const final=prepared(family,'final-revocation');assert.equal(active(final,'admit',{},'revoke-after-admission').ok,false);assert.equal(truth(final),2);assert.equal(active(final,'cancel',{reason:'operator_cancelled'}).ok,false);proofs.push(family+'-final-revalidation');
}

for(const family of (process.env.SEQUENTIAL_ADMISSION_ONLY?[]:families)){
 const d=prepared(family,'rebound-expiry',{evidence_seconds:12});await pause(1100);assert.equal(refresh(d).ok,true);assert.equal(active(d,'rebind').ok,true);await pause(12100);assert.equal(active(d,'admit').ok,false);assert.equal(truth(d),2);proofs.push(family+'-expiry-after-rebind');
 const unknown=setup(family,'unknown-prefix'),cfg=read(join(unknown,'host.json'));if(family==='git')git(unknown,['update-ref','refs/kujo-targets/'+cfg.intents[1].target_sha256,cfg.old_oid]);else command('sqlite3',[join(unknown,'sink.db'),'DELETE FROM logical_effects;']);assert.equal(refresh(unknown).ok,true);assert.equal(select(unknown).ok,false);proofs.push(family+'-live-prefix-uncertainty-blocks');
 const orphan=prepared(family,'orphan');const v=inspect(orphan),pointer=read(join(orphan,'pointer.json'));fs.writeFileSync(join(pointer.run_dir,'effect-lifecycle',v.lifecycle.active+'.claim'),'orphan',{flag:'wx'});for(const operation of ['rebind','cancel','admit'])assert.equal(active(orphan,operation,operation==='cancel'?{reason:'operator_cancelled'}:{}).ok,false);assert.equal(truth(orphan),2);proofs.push(family+'-orphan-claim-blocks');
 const stale=prepared(family,'stale-pre-C');const before=expectedRequest(stale,'select',{effect_id:'D'});assert.equal(active(stale,'admit').ok,true);assert.equal(run(stale,before).ok,false);assert.equal(refresh(stale).ok,true);assert.equal(run(stale,before).ok,false);proofs.push(family+'-pre-C-cursor-cannot-select-D');
 const retained=prepared(family,'missing-evidence'),rv=inspect(retained),rp=read(join(retained,'pointer.json'));const basis=read(join(rp.run_dir,'effect-lifecycle',rv.lifecycle.basis_ref.slice(7)+'.json'));fs.unlinkSync(join(rp.run_dir,'effect-lifecycle',basis.observations[0].slice(7)+'.json'));assert.equal(active(retained,'admit').ok,false);assert.equal(truth(retained),2);proofs.push(family+'-retained-evidence-required');
}

const canonical=x=>Array.isArray(x)?'['+x.map(canonical).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}':JSON.stringify(x);
function alterState(d,change){const p=join(read(join(d,'pointer.json')).run_dir,'state.json');const v=JSON.parse(fs.readFileSync(p,'utf8').split('\n').slice(1).join('\n'));change(v);fs.writeFileSync(p,'DISPATCH_ASSURANCE_STATE_V1BETA1\n'+canonical(v));snapshots.delete(d)}
for(const family of (process.env.SEQUENTIAL_ADMISSION_ONLY?[]:families)){
 for(const mode of ['expire-after-admission','registration-after-admission']){const d=prepared(family,mode,{evidence_seconds:12});assert.equal(active(d,'admit',{},mode).ok,false);assert.equal(truth(d),2);assert.equal(active(d,'cancel',{reason:'operator_cancelled'}).ok,false);proofs.push(family+'-'+mode)}
 for(const field of ['revision','journal','allowed-actions','effect-state','parent-attempt']){const d=prepared(family,'state-'+field),v=inspect(d);alterState(d,s=>{if(field==='revision'){s.revision++;s.human_intervention.state_revision++}if(field==='journal')s.control_journal.last_sha256=hash('bad');if(field==='allowed-actions')s.human_intervention.allowed_actions=['abort'];if(field==='effect-state')s.steps[0].execution_result.effects[2].state='started';if(field==='parent-attempt')s.steps[0].control_attempt=2});assert.equal(run(d,{operation:'admit',expected:v.cursor,attempt_id:v.lifecycle.active}).ok,false);if(field==='revision'||field==='journal')assert.equal(inspect(d).ok,false);assert.equal(truth(d),2);proofs.push(family+'-state-'+field)}
 const parent=prepared(family,'parent-replay');assert.equal(JSON.parse(command(kujo,['run','tests/sequential_effect_fixture.kujo',parent,'generic'])).ok,false);assert.equal(truth(parent),2);proofs.push(family+'-parent-replay-denied');
}
if(!process.env.SEQUENTIAL_ADMISSION_ONLY&&process.env.SEQUENTIAL_FAMILY!=='git'){
// A real pre-lifecycle reader must refuse the additive required feature.
const older=join(root,'old-reader');fs.mkdirSync(older);const archive=spawnSync('git',['archive','9f700059767730feffc05cb4ae26c649fe70dc0a'],{maxBuffer:64*1024*1024});assert.equal(archive.status,0);assert.equal(spawnSync('tar',['-x','-C',older],{input:archive.stdout}).status,0);fs.writeFileSync(join(older,'probe.kujo'),'from src.core.state import load_run_state\nargs := args()\ntry {print(to_json(load_run_state(args[0],args[1])))} except err {print(to_json({"ok":false}))}\n');
const incompatible=prepared('sqlite','old-reader'),ip=read(join(incompatible,'pointer.json'));const old=spawnSync(kujo,['run','probe.kujo',join(incompatible,'runs'),ip.run_id],{cwd:older,env,encoding:'utf8',timeout:60000});assert.equal(old.status,0,old.stderr);assert.equal(JSON.parse(old.stdout).ok,false);proofs.push('actual-old-reader-refuses-lifecycle');
env.DISPATCH_STATE_BACKEND='sqlite';const database=prepared('sqlite','sqlite-state');delete env.DISPATCH_STATE_BACKEND;fs.writeFileSync(join(read(join(database,'pointer.json')).run_dir,'state.json'),'{}');assert.equal(active(database,'admit').ok,true);assert.equal(refresh(database).ok,true);assert.equal(select(database,'D').ok,true);assert.equal(active(database,'admit').ok,true);proofs.push('sqlite-authority-over-json-mirror');
}

for(const family of families){
 const d=prepared(family,'two-admissions'),v=inspect(d),request={operation:'admit',expected:v.cursor,attempt_id:v.lifecycle.active};
 const results=await race(d,[request,request]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(truth(d),3);
 const p=read(join(d,'pointer.json')),s=JSON.parse(fs.readFileSync(join(p.run_dir,'state.json'),'utf8').split('\n').slice(1).join('\n'));
 const events=s.effect_lifecycle.map(ref=>read(join(p.run_dir,'effect-lifecycle',ref.slice(7)+'.json')));assert.equal(events.filter(e=>e.kind==='admitted').length,1);
 assert.equal(fs.readdirSync(join(p.run_dir,'effect-lifecycle')).filter(f=>f.endsWith('.claim')).length,1);proofs.push(family+'-two-fresh-controllers-one-admission');
}
console.log(JSON.stringify({ok:true,root,checks:proofs.length,proofs}));
