import {fs,join,setup,program,evaluator,human,edge,accepted,policy,run,state,assert,finishProgram,finishEval,finishHuman,finishGraph,gop,pop,apply,actor,patch,read,write} from './static_policy_helpers.mjs';
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)},denied=x=>assert.equal(x.ok,false,JSON.stringify(x));
const group={id:'RepairFlow',members:['R1','E','R2'],entry:['A'],policy:'required-success'};
const d=setup('subgraph',[program('A'),program('R1',['A'],[edge('A')]),evaluator('E','R1'),program('R2',['E'],[edge('R1')]),{...program('B',['R1','E','R2'],[edge('R2')]),after_subgraphs:['RepairFlow']}],{graph_policy:policy([],[group])});
run(d,'drive');finishProgram(d,'A');run(d,'drive');finishProgram(d,'R1');run(d,'drive');patch(join(d,'E','host.json'),v=>v.expected_value=2);finishEval(d,'E');run(d,'drive');finishProgram(d,'R2');run(d,'drive');assert.equal(state(d,'B').node_execution_admission,undefined);assert.equal(state(d).subgraph_finalizations,undefined);assert.equal(gop(d,'graph-assess').candidate.outcome,'blocked');assert.equal(pop(d,'subgraph','RepairFlow').candidate.outcome,'completed');pass('all internal facts without subgraph terminal event block parent');
const plan=run(d,'op','graph',{operation:'recovery-plan'});assert.equal(plan.ok,true,JSON.stringify(plan));assert.equal(plan.plan.repairs.length,0);assert.equal(state(d).subgraph_finalizations,undefined);pass('recovery cannot invent subgraph completion');
apply(d,'subgraph','RepairFlow');assert.equal(state(d,'B').node_execution_admission,undefined);run(d,'drive');assert.ok(state(d,'B').node_execution_admission);const bound=state(d,'B').node_input_binding;assert.equal(bound.policy.subgraphs.length,1);assert.equal(bound.predecessors.length,0);assert.equal(bound.inputs[0].producer_node,'R2');pass('parent binds exact subgraph receipt and output without copying internal terminal list');
finishProgram(d,'B');run(d,'drive');assert.equal(finishGraph(d).outcome,'completed');assert.equal(state(d).subgraph_finalizations.RepairFlow.candidate.nodes.length,3);assert.equal(read(join(d,'B','output.json')).value,4);pass('subgraph provenance and independent parent execution survive graph finalization');
const budget=setup('budget-block',[program('A'),program('B',['A'],[edge('A')])],{graph_policy:policy([],[],1)});run(budget,'drive');finishProgram(budget,'A');run(budget,'drive');const ba=gop(budget,'graph-assess');assert.equal(ba.candidate.outcome,'blocked');assert.deepEqual(ba.candidate.budget,{unit:'program_dispatch_reservations',used:1,limit:1,exhausted:true,on_exhaustion:'block'});assert.equal(state(budget,'B').node_execution_admission,undefined);assert.equal(state(budget,'A').parent_finalization.candidate.outcome,'completed');pass('budget exhaustion blocks new dispatch but permits consumed A resolution');
const definition=join(budget,'graph.json'),saved=read(definition);patch(definition,v=>v.graph_policy.budget.max_program_dispatches=2);denied(run(budget,'drive'));write(definition,saved);pass('budget ceiling cannot be raised through a mutable workflow');
const original=fs.readFileSync(join(state(budget).run_dir,'state.json')),header=original.toString().split('\n')[0],tampered=state(budget);tampered.workflow_definition.metadata.graph_policy.budget.max_program_dispatches=2;fs.writeFileSync(join(tampered.run_dir,'state.json'),header+'\n'+JSON.stringify(tampered));denied(gop(budget,'graph-assess'));fs.writeFileSync(join(tampered.run_dir,'state.json'),original);pass('anchored budget mutation rejects after run start');
const reviewSource={...human('H',[]),on_unsuccessful:{action:'require_review',review_node:'H2'}};
const rev=setup('failure-requires-review',[reviewSource,accepted(human('H2',['H']),'H',['rejected'])],{graph_policy:policy()});run(rev,'drive');finishHuman(rev,'H','abort');run(rev,'drive');assert.equal(gop(rev,'graph-assess').candidate.outcome,'blocked');finishHuman(rev,'H2');assert.equal(finishGraph(rev).outcome,'completed');assert.equal(state(rev).node_completions.H.terminal.outcome,'rejected');pass('explicit failure-review strategy requires new authorized decision and preserves denial');
for(const action of ['fail','block']){const x=setup('required-'+action,[{...human('H',[]),on_unsuccessful:{action}}],{graph_policy:policy()});run(x,'drive');finishHuman(x,'H','abort');const a=gop(x,'graph-assess');assert.equal(a.candidate.outcome,action==='fail'?'failed':'blocked');if(action==='fail')assert.equal(finishGraph(x).outcome,'failed');pass('required terminal rejection follows explicit '+action+' policy')}
const fan=setup('fanout-optional-failure',[program('A'),human('B',['A']),{...human('C',['A']),optional:true,on_unsuccessful:{action:'continue_optional'}},human('D',['A'])],{graph_policy:policy()});run(fan,'drive');finishProgram(fan,'A');run(fan,'drive');finishHuman(fan,'B');finishHuman(fan,'C','abort');finishHuman(fan,'D');assert.equal(finishGraph(fan).outcome,'completed');assert.equal(state(fan).node_completions.C.terminal.outcome,'rejected');assert.equal(state(fan,'A').parent_finalization.candidate.outcome,'completed');pass('fanout optional rejection remains history while required siblings succeed');
const sealed=setup('failed-subgraph-sealed',[human('A',[]),human('R1',['A']),human('R2',['A']),{...human('B',['R1','R2']),after_subgraphs:['SG']}],{graph_policy:policy([],[{id:'SG',members:['R1','R2'],entry:['A'],policy:'required-success'}])});run(sealed,'drive');finishHuman(sealed,'A');run(sealed,'drive');finishHuman(sealed,'R1','abort');assert.equal(pop(sealed,'subgraph','SG').candidate.outcome,'failed');apply(sealed,'subgraph','SG');denied(gop(sealed,'review-open',{node_id:'R2'}));run(sealed,'drive');assert.equal(state(sealed).node_completions.R2,undefined);assert.equal(state(sealed).graph_node_bindings.B,undefined);assert.equal(finishGraph(sealed).outcome,'failed');pass('failed subgraph terminal seals unfinished unconsumed members and blocks parent');
console.log(JSON.stringify({ok:true,checks:proofs.length,scenarios:proofs}));
