import {fs,join,resolve,spawn,assert,kujo,root,env,write,fixture,run,state,setup,program,human,policy,branch,routed,accepted,gop,pop,apply,actor,finishHuman,op,command,finalize} from './static_policy_helpers.mjs';
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)};let serial=0;
async function fresh(d,request={},extra={},marker=null,mode='policy-op',id='graph'){
 const file=join(d,'fresh-'+serial+++'.json');write(file,request);
 return await new Promise((done,reject)=>{const p=spawn(kujo,['run',fixture,d,mode,id,file],{env:{...env,...extra}});let out='',err='';const timer=setTimeout(()=>p.kill('SIGKILL'),180000);p.stdout.on('data',b=>{out+=b;if(marker&&out.includes(marker))p.kill('SIGKILL')});p.stderr.on('data',b=>err+=b);p.on('close',(code,signal)=>{clearTimeout(timer);try{assert.equal(err,'');if(marker){assert.ok(out.includes(marker),out);assert.equal(signal,'SIGKILL');done(null)}else{assert.equal(code,0,out);done(JSON.parse(out))}}catch(e){reject(e)}})})
}
function repair(d){const p=run(d,'op','graph',{operation:'recovery-plan'});assert.equal(p.ok,true,JSON.stringify(p));assert.ok(p.plan.repairs.length);const r=run(d,'op','graph',{operation:'recovery-apply',plan:p.plan});assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.continuation,'not_authorized')}
const original=process.cwd(),controllers=join(root,'controllers'),copy=join(controllers,'dispatch');fs.mkdirSync(copy,{recursive:true});fs.cpSync(resolve('src'),join(copy,'src'),{recursive:true});fs.mkdirSync(join(copy,'tests'));fs.copyFileSync(resolve(fixture),join(copy,fixture));for(const dir of ['schemas','examples'])fs.symlinkSync(resolve(dir),join(copy,dir));for(const name of ['workcell','eval'])fs.symlinkSync(resolve('../'+name),join(controllers,name));
const journal=join(copy,'src/core/control_journal.kujo');let code=fs.readFileSync(journal,'utf8'),point='    append_file(path, line)';assert.ok(code.includes(point));fs.writeFileSync(journal,code.replace(point,'    if env("POLICY_RECORD_CRASH") == kind {print("CRASH:immutable-policy-record");sleep(30000)}\n'+point));process.chdir(copy);env.KUJO_MODULE_PATH=[copy,resolve(original,'..'),resolve(original,'../workcell'),resolve(original,'../eval')].join(':');
function branchRun(name,programs=false){const b=programs?program('B',['H']):human('B',['H']);const d=setup(name,[routed(human('H',[]),'choice'),b,accepted(human('S',['H']),'H',['rejected'])],{graph_policy:policy([branch('choice','H','human_action',{approve_override:['B'],abort:['S']})])});run(d,'drive');finishHuman(d,'H');return d}
const d=branchRun('branch-race-and-consumption',true);let a=pop(d,'branch','choice');await fresh(d,{kind:'branch',id:'choice',operation:'apply',candidate:a.candidate,actor},{NODE_CRASH:'before_branch'},'CRASH:before_branch');assert.equal(state(d).branch_activations,undefined);const rp=run(d,'op','graph',{operation:'recovery-plan'});assert.equal(rp.plan.repairs.length,0);assert.equal(state(d).branch_activations,undefined);pass('condition fact and crash before activation do not let recovery invent a path');
const ca=await Promise.all([fresh(d,{kind:'branch',id:'choice',operation:'assess'}),fresh(d,{kind:'branch',id:'choice',operation:'assess'})]);assert.ok(ca.every(v=>v.ok));const race=await Promise.all(ca.map(v=>fresh(d,{kind:'branch',id:'choice',operation:'apply',candidate:v.candidate,actor})));assert.equal(race.filter(v=>v.ok).length,1,JSON.stringify(race));assert.match(race.find(v=>!v.ok).reason||JSON.stringify(race.find(v=>!v.ok)),/locked|activated|lock/i);let events=fs.readFileSync(join(state(d).run_dir,'control-events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(events.filter(v=>v.kind==='graph_branch_activated').length,1);pass('two fresh controllers publish exactly one branch activation');
await fresh(d,{}, {NODE_TARGET:'B',NODE_CRASH:'after_node_start_requested'},'CRASH:after_node_start_requested','drive');await fresh(d,{}, {NODE_CRASH:'after_node_admission'},'CRASH:after_node_admission','start','B');assert.ok(state(d,'B').node_execution_admission);assert.equal(fs.existsSync(join(d,'B','executions.log')),false);assert.equal((await fresh(d,{}, {},null,'start','B')).ok,false);run(d,'drive');assert.equal(fs.existsSync(join(d,'B','executions.log')),false);assert.equal(gop(d,'graph-assess').candidate.outcome,'blocked');assert.equal(pop(d,'branch','choice').ok,false);pass('consumed downstream attempt cannot retry or change branch after crash');
const lost=branchRun('selected-effect-lost-reply',true);apply(lost,'branch','choice');run(lost,'drive');assert.equal(op(lost,'B','refresh',{effect_id:'C'}).ok,true);assert.equal(op(lost,'B','select',{effect_id:'C'}).ok,true);const selected=run(lost,'op','B',{operation:'inspect'}),attempt=selected.lifecycle.active;await fresh(lost,{operation:'admit',expected:selected.cursor,attempt_id:attempt},{NODE_CRASH:'after_mutation'},'CRASH:after_mutation','op','B');assert.equal(Number(command('sqlite3',[join(lost,'B','sink.db'),'SELECT count(*) FROM mutation_audit;'])),1);const uncertain=run(lost,'op','B',{operation:'inspect'});assert.equal(op(lost,'B','admit',{attempt_id:attempt}).ok,false);assert.equal(gop(lost,'graph-assess').candidate.outcome,'blocked');assert.equal(op(lost,'B','verify',{attempt_id:attempt}).ok,true);assert.equal(op(lost,'B','refresh',{effect_id:'C'}).ok,true);finalize(lost,'B');run(lost,'drive');assert.equal(Number(command('sqlite3',[join(lost,'B','sink.db'),'SELECT count(*) FROM mutation_audit;'])),1);assert.equal(state(lost).branch_activations.choice.candidate.selected,'approve_override');pass('lost selected effect reply stays consumed; independent SQLite verification resolves it without retry');
for(const crash of ['after_branch','immutable']){const x=branchRun('activation-'+crash);a=pop(x,'branch','choice');await fresh(x,{kind:'branch',id:'choice',operation:'apply',candidate:a.candidate,actor},crash==='immutable'?{POLICY_RECORD_CRASH:'graph_branch_activated'}:{NODE_CRASH:crash},crash==='immutable'?'CRASH:immutable-policy-record':'CRASH:'+crash);if(crash==='immutable'){assert.equal(state(x).branch_activations,undefined);repair(x)}assert.equal(state(x).branch_activations.choice.candidate.selected,'approve_override');assert.equal(state(x).graph_finalization,undefined);pass('branch '+crash+' retains exact path without continuation')}
function groupRun(name){const x=setup(name,[human('A',[]),human('R1',['A']),human('R2',['R1']),{...human('B',['R1','R2']),after_subgraphs:['SG']}],{graph_policy:policy([],[{id:'SG',members:['R1','R2'],entry:['A'],policy:'required-success'}])});run(x,'drive');finishHuman(x,'A');run(x,'drive');finishHuman(x,'R1');run(x,'drive');finishHuman(x,'R2');run(x,'drive');assert.equal(state(x).graph_node_bindings.B,undefined);return x}
const sg=groupRun('subgraph-race');assert.equal(state(sg).subgraph_finalizations,undefined);assert.equal(run(sg,'op','graph',{operation:'recovery-plan'}).plan.repairs.length,0);const plans=await Promise.all([fresh(sg,{kind:'subgraph',id:'SG',operation:'assess'}),fresh(sg,{kind:'subgraph',id:'SG',operation:'assess'})]);const finals=await Promise.all(plans.map(v=>fresh(sg,{kind:'subgraph',id:'SG',operation:'apply',candidate:v.candidate,actor})));assert.equal(finals.filter(v=>v.ok).length,1,JSON.stringify(finals));events=fs.readFileSync(join(state(sg).run_dir,'control-events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(events.filter(v=>v.kind==='graph_subgraph_finalized').length,1);run(sg,'drive');assert.ok(state(sg).graph_node_bindings.B.policy.subgraphs.length);pass('fresh subgraph finalizers race for one receipt; parent then binds it');
for(const crash of ['after_subgraph','immutable']){const x=groupRun('subgraph-'+crash);a=pop(x,'subgraph','SG');await fresh(x,{kind:'subgraph',id:'SG',operation:'apply',candidate:a.candidate,actor},crash==='immutable'?{POLICY_RECORD_CRASH:'graph_subgraph_finalized'}:{NODE_CRASH:crash},crash==='immutable'?'CRASH:immutable-policy-record':'CRASH:'+crash);if(crash==='immutable'){assert.equal(state(x).subgraph_finalizations,undefined);repair(x)}assert.equal(state(x).subgraph_finalizations.SG.candidate.outcome,'completed');assert.equal(state(x).graph_node_bindings.B,undefined);run(x,'drive');assert.ok(state(x).graph_node_bindings.B);pass('subgraph '+crash+' survives exact recovery without implied parent execution')}
process.chdir(original);console.log(JSON.stringify({ok:true,checks:proofs.length,scenarios:proofs,root}));
