import {fs,join,setup,program,evaluator,human,edge,routed,accepted,policy,branch,run,state,assert,finishProgram,finishEval,finishHuman,finishGraph,gop,pop,apply,actor,patch,read,write,humanDecision} from './static_policy_helpers.mjs';
const proofs=[];const pass=x=>{proofs.push(x);console.log('PASS '+x)},denied=x=>assert.equal(x.ok,false,JSON.stringify(x));
for(const verdict of ['pass','fail']){
 const nodes=[program('A'),routed(evaluator('E','A'),'quality'),program('B',['E'],[edge('A')]),accepted(program('R',['E'],[edge('A')]),'E',['failed']),evaluator('E2','R'),program('C',['B','E2'],[edge('A')])];
 const d=setup('eval-branch-'+verdict,nodes,{graph_policy:policy([branch('quality','E','evaluation_verdict',{pass:['B'],fail:['R','E2']})])});
 run(d,'drive');finishProgram(d,'A');run(d,'drive');denied(pop(d,'branch','quality'));pass('unfinalized Eval cannot activate '+verdict);
 if(verdict==='fail')patch(join(d,'E','host.json'),v=>v.expected_value=99);
 run(d,'evaluate','E');const path=join(d,'E','evaluation.json'),original=read(path);patch(path,v=>v.input_evidence_ids[0]='sha256:'+'0'.repeat(64));denied(gop(d,'node-assess',{node_id:'E'}));denied(pop(d,'branch','quality'));write(path,original);patch(path,v=>v.subject.run_id='wrong-producer');denied(gop(d,'node-assess',{node_id:'E'}));denied(pop(d,'branch','quality'));write(path,original);finishEval(d,'E');
 const a=pop(d,'branch','quality');assert.equal(a.ok,true,JSON.stringify(a));assert.equal(a.candidate.selected,verdict);assert.equal(gop(d,'graph-assess').candidate.outcome,'blocked');
 run(d,'drive');assert.equal(state(d,'B').node_execution_admission,undefined);assert.equal(state(d,'R').node_execution_admission,undefined);denied(pop(d,'branch','quality','apply',{candidate:a.candidate,actor}));pass('stale assessment and scheduling without activation reject '+verdict);
 const live=pop(d,'branch','quality');denied(pop(d,'branch','quality','apply',{candidate:live.candidate,actor},{GRAPH_REVOKE:'before_branch'}));patch(join(d,'host.json'),v=>v.operator_enabled=true);apply(d,'branch','quality');const definitionPath=join(d,'graph.json'),definition=read(definitionPath);patch(definitionPath,v=>v.graph_policy.branches[0].cases.reverse());denied(run(d,'drive'));write(definitionPath,definition);const selected=verdict==='pass'?'B':'R',inactive=verdict==='pass'?'R':'B';assert.equal(state(d,selected).node_execution_admission,undefined);denied(run(d,'op',inactive,{operation:'inputs-assess'}));run(d,'drive');assert.ok(state(d,selected).node_execution_admission);assert.equal(state(d,selected).effect_lifecycle,undefined);pass('only selected path independently admitted '+verdict);
 denied(pop(d,'branch','quality','apply',{candidate:{...a.candidate,selected:verdict==='pass'?'fail':'pass'},actor}));patch(path,v=>v.verdict=verdict==='pass'?'fail':'pass');denied(pop(d,'branch','quality'));assert.equal(state(d).branch_activations.quality.candidate.selected,verdict);write(path,original);pass('alternate later evaluation cannot flap consumed branch '+verdict);
 finishProgram(d,selected);run(d,'drive');if(verdict==='fail'){patch(join(d,'E2','host.json'),v=>v.expected_value=2);finishEval(d,'E2');run(d,'drive');assert.equal(state(d,'A').steps[0].attempts,1);pass('repair is new R execution and new E2 judgment, never retry A')}
 assert.ok(state(d,'C').node_execution_admission);assert.equal(state(d,'C').node_input_binding.policy.branches.length,1);assert.equal(state(d,'C').node_input_binding.predecessors.length,1);finishProgram(d,'C');run(d,'drive');assert.equal(finishGraph(d).outcome,'completed');assert.equal(state(d,inactive).node_execution_admission,undefined);assert.equal(state(d).graph_finalization.candidate.nodes.find(n=>n.node_id===inactive).reason,'not_selected');assert.equal(state(d).steps.find(n=>n.id===inactive).status,'pending');pass('conditional join and outcome omit inactive without success '+verdict);
}
for(const action of ['approve_override','abort']){
 const d=setup('human-branch-'+action,[program('A'),routed(human('H',['A'],[edge('A')]),'review'),program('B',['H'],[edge('A')]),accepted(program('S',['H'],[edge('A')]),'H',['rejected'])],{graph_policy:policy([branch('review','H','human_action',{approve_override:['B'],abort:['S']})])});
 run(d,'drive');finishProgram(d,'A');run(d,'drive');const decision=humanDecision(d,'H',action);denied(gop(d,'node-assess',{node_id:'H',decision:{...decision,expected_state_revision:decision.expected_state_revision-1}}));denied(gop(d,'node-assess',{node_id:'H',decision:{...decision,subject:{...decision.subject,step_id:'A'}}}));denied(pop(d,'branch','review'));finishHuman(d,'H',action);apply(d,'branch','review');const selected=action==='abort'?'S':'B';assert.equal(state(d,selected).node_execution_admission,undefined);run(d,'drive');finishProgram(d,selected);run(d,'drive');assert.equal(finishGraph(d).outcome,'completed');assert.equal(state(d).node_completions.H.terminal.outcome,action==='abort'?'rejected':'completed');pass('authorized human '+action+' routes without direct execution or rewritten decision');
}
console.log(JSON.stringify({ok:true,checks:proofs.length,scenarios:proofs}));
