#!/usr/bin/env bash
set -euo pipefail

KUJO_BIN="${KUJO_BIN:-kujo}"
SHARD_COUNT="${DISPATCH_TEST_SHARDS:-24}"
SHARD_DIR="tests/tmp/dispatch-test-shards"
SOURCE_TEST="tests/dispatch_tests.kujo"

if [[ ! "$SHARD_COUNT" =~ ^[0-9]+$ ]] || [[ "$SHARD_COUNT" -lt 1 ]]; then
	echo "DISPATCH_TEST_SHARDS must be a positive integer."
	exit 1
fi

if [[ -d "$SHARD_DIR" ]]; then
	find "$SHARD_DIR" -type f -delete
fi
mkdir -p "$SHARD_DIR"

awk -v out_dir="$SHARD_DIR" -v shard_count="$SHARD_COUNT" '
BEGIN {
	test_count = 0
	in_tests = 0
	setup = ""
}
/^test "/ {
	if (in_tests == 0) {
		for (i = 1; i <= shard_count; i++) {
			path = out_dir "/dispatch_tests_shard_" i ".kujo"
			print "# Generated by scripts/run_release_gate.sh from tests/dispatch_tests.kujo." > path
			print setup >> path
			close(path)
		}
		in_tests = 1
	}
	test_count += 1
}
{
	if (in_tests == 0) {
		setup = setup $0 "\n"
	} else {
		shard = ((test_count - 1) % shard_count) + 1
		path = out_dir "/dispatch_tests_shard_" shard ".kujo"
		print $0 >> path
		close(path)
	}
}
END {
	if (test_count == 0) {
		print "No tests discovered in " ARGV[1] > "/dev/stderr"
		exit 2
	}
	print test_count
}
' "$SOURCE_TEST" > "$SHARD_DIR/test-count.txt"

total_tests="$(cat "$SHARD_DIR/test-count.txt")"
echo "Dispatch release gate"
echo "Runtime: $KUJO_BIN"
echo "Shards: $SHARD_COUNT"
echo "Source tests: $total_tests"

echo
echo "Running focused integration suites..."
"$KUJO_BIN" test-run tests/sdk_adapter_tests.kujo -v
"$KUJO_BIN" test-run tests/policy_precedence_tests.kujo -v
"$KUJO_BIN" test-run tests/routing_tests.kujo -v
DISPATCH_STATE_BACKEND=sqlite "$KUJO_BIN" test-run tests/state_store_sqlite_tests.kujo -v
"$KUJO_BIN" test-run tests/operational_controls_tests.kujo -v

echo
echo "Running sharded Dispatch contract suite..."
index=1
while [[ "$index" -le "$SHARD_COUNT" ]]; do
	shard_file="$SHARD_DIR/dispatch_tests_shard_${index}.kujo"
	echo "Shard $index/$SHARD_COUNT: $shard_file"
	"$KUJO_BIN" test-run "$shard_file" -v
	index=$((index + 1))
done

echo
echo "Running command-surface smoke..."
vm_stderr="$SHARD_DIR/vm-command.stderr"
interpreter_stderr="$SHARD_DIR/interpreter-command.stderr"
: > "$vm_stderr"
: > "$interpreter_stderr"
"$KUJO_BIN" run dispatch.kujo --help >/dev/null 2>"$vm_stderr"
"$KUJO_BIN" run dispatch.kujo version >/dev/null 2>>"$vm_stderr"
"$KUJO_BIN" run dispatch.kujo --interpreter -- --help >/dev/null 2>"$interpreter_stderr"
"$KUJO_BIN" run dispatch.kujo --interpreter -- version >/dev/null 2>>"$interpreter_stderr"
if [[ -s "$vm_stderr" || -s "$interpreter_stderr" ]]; then
	echo "Dispatch command surface emitted diagnostics." >&2
	cat "$vm_stderr" "$interpreter_stderr" >&2
	exit 1
fi

kennel_version="$(grep -E '^version' kennel.toml | head -1 | sed -E 's/.*"(.*)".*/\1/')"
kujo_version="$(grep -E '^version' kujo.toml | head -1 | sed -E 's/.*"(.*)".*/\1/')"
reported_version="$(DISPATCH_ROOT="$PWD" "$KUJO_BIN" run "$PWD/dispatch.kujo" -- version)"
if [[ "$kennel_version" != "$kujo_version" || "$reported_version" != "Dispatch $kennel_version" ]]; then
	echo "Dispatch package version mismatch: kennel=$kennel_version kujo=$kujo_version reported=$reported_version" >&2
	exit 1
fi

echo
echo "Running bounded release workload evidence..."
DISPATCH_SOAK_RUNS="${DISPATCH_SOAK_RUNS:-3}" "$PWD/scripts/run_v1_1_evidence.sh"

echo "Dispatch release gate passed."
