#!/usr/bin/env bash
set -euo pipefail

KUJO_BIN="${KUJO_BIN:-kujo}"
KUJO_BIN="$KUJO_BIN" bash scripts/check_runtime_contract.sh
SHARD_COUNT="${DISPATCH_TEST_SHARDS:-24}"
SHARD_DIR="tests/tmp/dispatch-test-shards"
SOURCE_TEST="tests/dispatch_tests.kujo"

if [[ ! "$SHARD_COUNT" =~ ^[0-9]+$ ]] || [[ "$SHARD_COUNT" -lt 1 ]]; then
	echo "DISPATCH_TEST_SHARDS must be a positive integer."
	exit 1
fi

if [[ -d "$SHARD_DIR" ]]; then
	find "$SHARD_DIR" -type f -delete
fi
mkdir -p "$SHARD_DIR"

awk -v out_dir="$SHARD_DIR" -v shard_count="$SHARD_COUNT" '
BEGIN {
	test_count = 0
	in_tests = 0
	setup = ""
}
/^test "/ {
	if (in_tests == 0) {
		for (i = 1; i <= shard_count; i++) {
			path = out_dir "/dispatch_tests_shard_" i ".kujo"
			print "# Generated by scripts/run_release_gate.sh from tests/dispatch_tests.kujo." > path
			print setup >> path
			close(path)
		}
		in_tests = 1
	}
	test_count += 1
}
{
	if (in_tests == 0) {
		setup = setup $0 "\n"
	} else {
		shard = ((test_count - 1) % shard_count) + 1
		path = out_dir "/dispatch_tests_shard_" shard ".kujo"
		print $0 >> path
		close(path)
	}
}
END {
	if (test_count == 0) {
		print "No tests discovered in " ARGV[1] > "/dev/stderr"
		exit 2
	}
	print test_count
}
' "$SOURCE_TEST" > "$SHARD_DIR/test-count.txt"

total_tests="$(cat "$SHARD_DIR/test-count.txt")"
echo "Dispatch release gate"
echo "Runtime: $KUJO_BIN"
echo "Shards: $SHARD_COUNT"
echo "Source tests: $total_tests"

echo
echo "Running smoke-gate regression checks..."
bash tests/source_layout_tests.sh
bash tests/smoke_gate_tests.sh
KUJO_BIN="$KUJO_BIN" bash tests/run_lock_concurrency_tests.sh
KUJO_BIN="$KUJO_BIN" bash tests/webhook_sink_concurrency_tests.sh
KUJO_BIN="$KUJO_BIN" bash tests/bridge_process_tests.sh
KUJO_BIN="$KUJO_BIN" bash tests/showcase_walkthrough_tests.sh

echo "Running focused integration suites..."
mkdir -p "$SHARD_DIR/logs"
run_suite() {
	local name="$1"
	shift
	local log="$SHARD_DIR/logs/$name.log"
	local result=0
	"$@" >"$log" 2>&1 || result=$?
	if [[ "$result" -ne 0 ]]; then
		echo "$name failed (exit $result). Full evidence: $log" >&2
		tail -n 80 "$log" >&2
		return "$result"
	fi
	echo "$name passed. $(grep '^Tests:' "$log" | tail -1) Evidence: $log"
	if [[ "${DISPATCH_TEST_VERBOSE:-false}" == true ]]; then cat "$log"; fi
}
run_suite typescript_package npm --prefix interop/typescript-participant test
run_suite python_package interop/python-participant/.venv/bin/python -I interop/python-participant/run.py test
run_suite python_parity node tests/python_parity.mjs
run_suite python_isolation python3 tests/python_package_isolation.py
run_suite python_integration env KUJO_BIN="$KUJO_BIN" python3 tests/python_integration.py
run_suite typescript_after env KUJO_BIN="$KUJO_BIN" node tests/typescript_integration.mjs after_commit
run_suite typescript_before env KUJO_BIN="$KUJO_BIN" node tests/typescript_integration.mjs before_commit
run_suite control_boundary "$KUJO_BIN" test-run tests/control_boundary_tests.kujo -v
run_suite failure_gate_safety "$KUJO_BIN" test-run tests/failure_gate_safety_tests.kujo -v
run_suite failure_gate_execution "$KUJO_BIN" test-run tests/failure_gate_execution_tests.kujo -v
run_suite review_checkpoint "$KUJO_BIN" test-run tests/review_checkpoint_tests.kujo -v
run_suite persisted_negotiation_legacy "$KUJO_BIN" run tests/persisted_negotiation_legacy.kujo
run_suite persisted_negotiation_schemas "$KUJO_BIN" run tests/persisted_negotiation_schemas.kujo
run_suite persisted_negotiation_contracts "$KUJO_BIN" run tests/persisted_negotiation_contracts.kujo
run_suite persisted_negotiation env KUJO_BIN="$KUJO_BIN" node tests/persisted_negotiation_integration.mjs
run_suite persisted_negotiation_adapters env KUJO_BIN="$KUJO_BIN" node tests/persisted_negotiation_adapters.mjs
run_suite beta_contracts "$KUJO_BIN" run tests/beta_contracts.kujo
run_suite portable_commitments "$KUJO_BIN" run tests/portable_commitments.kujo tests/vectors/commitments.json tests/vectors/sqlite-commitments.json "${WORKCELL_ROOT:-../workcell}/tests/vectors/git-assurance-commitments.json" "${ABILITY_ROOT:-../ability}/tests/vectors/application-assurance-commitments.json"
run_suite portable_clean_room node tests/portable_clean_room.mjs
run_suite interop_oracles node tests/interop_oracle_integrity.mjs
run_suite interop_history "$KUJO_BIN" run tests/interop_history.kujo
run_suite git_participant_after env KUJO_BIN="$KUJO_BIN" node tests/git_participant_integration.mjs after_commit
run_suite git_participant_before env KUJO_BIN="$KUJO_BIN" node tests/git_participant_integration.mjs before_commit
run_suite http_response_loss env KUJO_BIN="$KUJO_BIN" node tests/http_ability_integration.mjs response-loss
run_suite http_timeout_before env KUJO_BIN="$KUJO_BIN" node tests/http_ability_integration.mjs timeout-before
run_suite http_application_error env KUJO_BIN="$KUJO_BIN" node tests/http_ability_integration.mjs application-error
run_suite mcp_ability env KUJO_BIN="$KUJO_BIN" node tests/mcp_ability_integration.mjs
run_suite mcp_stdio_loss env KUJO_BIN="$KUJO_BIN" node tests/mcp_ability_integration.mjs --lost-response
run_suite sdk_ability env KUJO_BIN="$KUJO_BIN" node tests/sdk_ability_integration.mjs
run_suite beta_migration env KUJO_BIN="$KUJO_BIN" node tests/beta_migration.mjs
run_suite assurance_compatibility "$KUJO_BIN" run tests/assurance_compatibility_tests.kujo
run_suite assurance_capabilities "$KUJO_BIN" run tests/assurance_capabilities_tests.kujo
run_suite effect_assurance_schema "$KUJO_BIN" run tests/effect_assurance_schema.kujo
run_suite effect_assurance env KUJO_BIN="$KUJO_BIN" node tests/effect_assurance_integration.mjs
run_suite ability_assurance env KUJO_BIN="$KUJO_BIN" bash tests/ability_assurance_integration.sh
run_suite reexecution_lifecycle "$KUJO_BIN" run tests/reexecution_lifecycle_fixture.kujo
run_suite decision_claim env KUJO_BIN="$KUJO_BIN" bash tests/decision_claim_contract.sh
run_suite sdk_adapter "$KUJO_BIN" test-run tests/sdk_adapter_tests.kujo -v
run_suite policy_precedence "$KUJO_BIN" test-run tests/policy_precedence_tests.kujo -v
run_suite retrieval_preferences "$KUJO_BIN" test-run tests/retrieval_preferences_tests.kujo -v
run_suite routing "$KUJO_BIN" test-run tests/routing_tests.kujo -v
DISPATCH_STATE_BACKEND=sqlite run_suite state_store_sqlite "$KUJO_BIN" test-run tests/state_store_sqlite_tests.kujo -v
run_suite operational_controls "$KUJO_BIN" test-run tests/operational_controls_tests.kujo -v
run_suite hardening "$KUJO_BIN" test-run tests/hardening_tests.kujo -v

echo
echo "Running sharded Dispatch contract suite..."
index=1
while [[ "$index" -le "$SHARD_COUNT" ]]; do
	shard_file="$SHARD_DIR/dispatch_tests_shard_${index}.kujo"
	echo "Shard $index/$SHARD_COUNT: $shard_file"
	run_suite "dispatch-$index" "$KUJO_BIN" test-run "$shard_file" -v
	index=$((index + 1))
done

echo
echo "Running command-surface smoke..."
vm_stderr="$SHARD_DIR/vm-command.stderr"
interpreter_stderr="$SHARD_DIR/interpreter-command.stderr"
: > "$vm_stderr"
: > "$interpreter_stderr"
"$KUJO_BIN" run dispatch.kujo --help >/dev/null 2>"$vm_stderr"
"$KUJO_BIN" run dispatch.kujo version >/dev/null 2>>"$vm_stderr"
"$KUJO_BIN" run dispatch.kujo --interpreter -- --help >/dev/null 2>"$interpreter_stderr"
"$KUJO_BIN" run dispatch.kujo --interpreter -- version >/dev/null 2>>"$interpreter_stderr"
if [[ -s "$vm_stderr" || -s "$interpreter_stderr" ]]; then
	echo "Dispatch command surface emitted diagnostics." >&2
	cat "$vm_stderr" "$interpreter_stderr" >&2
	exit 1
fi

kennel_version="$(grep -E '^version' kennel.toml | head -1 | sed -E 's/.*"(.*)".*/\1/')"
kujo_version="$(grep -E '^version' kujo.toml | head -1 | sed -E 's/.*"(.*)".*/\1/')"
reported_version="$(DISPATCH_ROOT="$PWD" "$KUJO_BIN" run "$PWD/dispatch.kujo" -- version)"
if [[ "$kennel_version" != "$kujo_version" || "$reported_version" != "Dispatch $kennel_version" ]]; then
	echo "Dispatch package version mismatch: kennel=$kennel_version kujo=$kujo_version reported=$reported_version" >&2
	exit 1
fi

echo
echo "Running bounded release workload evidence..."
DISPATCH_SOAK_RUNS="${DISPATCH_SOAK_RUNS:-3}" "$PWD/scripts/run_v1_1_evidence.sh"

echo "Dispatch release gate passed."
