from typing import Any, Mapping, Protocol
CONFORMANCE: str
class SDKError(ValueError):
    code: str
    def __init__(self, code: str) -> None: ...
class CorrelationError(SDKError): ...
class ParticipantCodec(Protocol):
    def encode_handoff(self, doc: Mapping[str, Any]) -> bytes: ...
    def parse_handoff(self, raw: bytes) -> dict[str, Any]: ...
    def match_expected(self, raw: bytes, expected: Mapping[str, Any]) -> bool: ...
    def provisional(self, doc: Mapping[str, Any]) -> bytes: ...
    def terminal_report(self, doc: Mapping[str, Any]) -> bytes: ...
    def finalize_after_readback(self, doc: Mapping[str, Any]) -> bytes: ...
def content_ref(raw: bytes) -> str: ...
def create_codec(registration: Mapping[str, Any]) -> ParticipantCodec: ...
